### ISSUE TITLE
Video files being downloaded multiple times

### ISSUE THREAD

**Issue by Jalbre2** [johanneszab/TumblThree#10]
I am seeing blogs redownload videos each time I run the program. This is causing lots of extra bandwidth to be taken up. I don't know if it is every video, or just reposts that point to the same file, but it's definitely happening. The exact same file names as the previous videos are being downloaded. I can generally cut all the new ones into the folder with the old and 95% of them are overwrites.

**Comment by johanneszab** [comment]
Thanks for sharing. I'll look into that at sometime this week.

**Comment by Jalbre2** [comment]
Looks like you fixed this too. Thanks!
