### ISSUE TITLE
'Download a url list' function does not work (Crash)

### ISSUE THREAD

**Issue by A-Cat-Named-Tiger** [johanneszab/TumblThree#100]
When I use 'Download a url list' function instead of downloading actual files, TumblThree freezes (or crashes) after retrieving first 25 urls. I am only trying to get image and video file links but it seems to have some problem on my computer.

**Comment by johanneszab** [comment]
Thanks for reporting. It's really time for unit tests now ... 

The date setting of the downloaded files truly doesn't work if there is no file downloaded at all but the url stored in a text file instead.
