### ISSUE TITLE
No longer working?

### ISSUE THREAD

**Issue by roweger** [johanneszab/TumblThree#105]
Maybe I'm missing something...but it doesn't seem to be working. I cannot get a single image to download.

I first tried v1.0.7.1 (which now looks to be removed from here), and it gave the error that you need to be logged in. So I clicked authenticate and was able to use the pop up window to enter the credentials. (On a side note, there doesn't seem to be an easy way to logout and login again with a different account. After logging in the first time, the authenticate button does nothing and I couldn't find any other way to reset what account to use.)

In any case, I entered a full URL, clicked add blog, and it appeared in the main window list. I clicked Crawl, which grays out that button and enables the Pause and Stop buttons...but nothing else seems to happen. There is no indication the app is doing anything. Progress never occurs.

It's the same with v1.0.6.8. I've tried several URLs.

https://dogs.tumblr.com
https://cars.tumblr.com
https://sports.tumblr.com

Nothing seems to work.

**Comment by johanneszab** [comment]
I've no idea what you people are always doing. No issues here what so ever:

![tumblthree](https://user-images.githubusercontent.com/1684561/27929278-9508b790-6292-11e7-9bbe-fd2550f2fae1.png)

> I first tried v1.0.7.1 (which now looks to be removed from here)

Yeah, I've removed it from the release site, but it's still linked in the latest release. I've had to because apparently some people cannot even read three sentences. I'll merge the download of private blogs that require a login with the non-login download at some point. But right now, it's probably better if I "hide" it in the latest release message.

**Comment by johanneszab** [comment]
I'll leave this open. Maybe someone else has this problem too and can help troubleshooting. I just remembered that someone was here 3 weeks ago with [an issue that sounded similar](https://github.com/johanneszab/TumblThree/issues/96).

**Comment by roweger** [comment]
Yeah, seems like the same issue...

> the other crawler I was using, referred to simply as Tumblr Image Downloader, had stopped working for me too, (which is what prompted me to find this program to begin with,)

That's my story exactly.

I'm running Windows 7, so it wouldn't seem to be a Windows 8 issue, as @Gho57X90 suspected. As you recommended in the other thread, I tried again with a "straight connection" to the Internet, direct ethernet cable to the modem, turning off the firewall and anything else that would manipulate connections. No luck.

I have another Windows 7 machine I can try, and could also run a virtual machine with XP and see how that goes.

I'm now really curious what this could be.

I'm wondering if the Tumblr Image Downloader app (that doesn't work for me and Gho57X90) will work for you and anyone else that TumblThree works for...

https://sourceforge.net/projects/tumblrimagedown/

**Comment by blezinski** [comment]
yeah i have this problem too, any new blogs i add (sfw or nsfw) show up as having 0 posts and wont crawl
i'm using 1.0.7.1 and W7

**Comment by johanneszab** [comment]
> yeah i have this problem too, any new blogs i add (sfw or nsfw) show up as having 0 posts and wont crawl
> i'm using 1.0.7.1 and W7

Could you try the v1.0.6.8 too? Because they work fundamentally different for the online/url crawling, it's nice to know whether or not both methods do not work. Than it's more likely being something with TumblThree.

Could you also try it (in both versions) with new, fresh settings and don't change them? You can temporarily rename the settings folder from C:\Users\Username\AppData\Local\TumblThree to something else and then restore it if it doesn't make any difference.

**Comment by johanneszab** [comment]
> yeah i have this problem too, any new blogs i add (sfw or nsfw) show up as having 0 posts and wont crawl
> i'm using 1.0.7.1 and W7

Okay, don't tell me you are still trying to download anything with the v1.0.7.1 without being logged in! Seeing [this issue](https://github.com/johanneszab/TumblThree/issues/104) combined with the text I've written in [the release](https://github.com/johanneszab/TumblThree/issues/4#issuecomment-313297515), it's quite clear to me why you cannot download.

Honestly, I'm currently thinking of stop developing all together or stop releasing anything new here. It me takes to write the code, explaining the current state/what is best, and then still people don't care to read the five sentences at all and run around and keep telling things are broken and I should troubleshoot their problems ..

I really hope I'm wrong with this ..

**Comment by blezinski** [comment]
yeah i authenticated 1.0.7.1 and it didnt work
1.0.6.8 works, ill delete the config folder and try the latest one again

**Comment by blezinski** [comment]
i deleted the appdata folder and 1.0.7.1 worked

**Comment by roweger** [comment]
I've tried both, v1.0.6.8 and authenticated v1.0.7.1, both with default settings (never messed with settings other than authenticating). Deleted the appdata folder upon retrying. Did v1.0.6.8 on a different Win7 machine...just ran the exe, pasted a URL, add blog, and clicked crawl...still no download.

I noticed @blezinski said his showed 0 posts. On mine it displays "number of downloads," but does nothing else. sports.tumblr.com shows 654, and dogs.tumblr.com shows 1141.

My next move will be to just do a fresh install of Win7 and test it from there. There may be something installed on both machines that is causing the issue. I'm not sure what it could be, but it'll be interesting to see if it works in that scenario.

**Comment by blezinski** [comment]
yeah mine displays 0 posts in the number of downloads column no matter if the blog works or not

**Comment by Ansel-Y** [comment]
Hello,how to use tumblthree?(I can not find 'TumblThree.exe' from 'TumblThree-1.0.6.11' folder downloaded from 'github'.)Should I buy this software from somewebsite?because it seems like that you all can use it effortlessly,maybe something is wrong~

**Comment by johanneszab** [comment]
https://github.com/johanneszab/TumblThree/releases/download/v1.0.6.11/TumblThree-v1.0.6.11.zip

You don't have to buy anything. And you should download it from this website. Just click the _TumblThree-v1.0.6.11.zip_ and not the link called _source code (zip)_.

**Comment by Ansel-Yue** [comment]
It works,thanks,it is really helpful for a confused beginner--me.Thank you again~
