### ISSUE TITLE
Settings not saving

### ISSUE THREAD

**Issue by Linktydraa** [johanneszab/TumblThree#108]
Hi Johannes,

I'm encountering another issue that I'm hoping has a really quick fix.

My settings are not saving properly. I'll change values here and there and hit save. Then if I close tumblthree and then open it back up, the settings revert to a former set, and not what I just saved them to be. Is there a way to fix this?

**Comment by tringate** [comment]
I can't be of much help as I don't experience the issue you are having.  Johannes may have some ideas.  
I am sure it would help him if you said what version of tumblthree you are running and if you are using portable mode or not.
The settings are saved in three files located in your:
C:/users/acctname/AppDate//local/tumblrthree/settings/ 
folder if you are not using portable mode and in your blog root file where the tumblrthree executable is located if you are using portable mode.  You might want to check those two areas to see if the file date changes when you set your settings.
The three file names are:
Manager.json
Queuelist.json
Settings.json

There is a note on the current release 6.14 saying that the settings now are set immediately  for most settings so he did do some code work in this area.

Tom

**Comment by johanneszab** [comment]
I also think it might be related to the _portable mode_.

If TumblThree finds any of the settings files (_settings.json_, _queue.json_) next to its executable location it will read those. Maybe you saved the settings with the portable mode deactivated. They will be update in the AppData location, but if you restarted TumblThree afterwards, the settings will not reflect the updated state as they are read from the local settings files next to the executable.

I haven't messed around with the settings code in the last weeks so I don't think it's broken in general and it works here properly.

As the last resort, as already mentioned, you simply might wipe your settings in *C:\Users\YourUsername\AppData\Local\TumblThree\\* and start with a fresh set of settings.

**Comment by Linktydraa** [comment]
What is the portable mode you all are talking about?

**Comment by tringate** [comment]
Portable mode can be found in settings on the "general" tab.

In windows, a program can save things it wants to "persist" from launch to launch.  This is just one of dozens of reasons to save information during run time.  Checking that box changes where tumblrthree saves this information.  By saving it in the windows "local" location the same information is used by any "instance" of the program as there is only a single copy of each file.  By saving it where the actual executable is located, you can have your program and blog files on something like a USB drive.  It also allows you to have several different "instances" of the program you can run and have different settings for each "instance".

I have not confirmed if it is possible to run multiple "instances" at the same time, that would be impossible if the settings information was saved in the windows AppData area.  With it saved where the executable is located multiple instances of tumblrthree may well be able to run at the same time.

The normal default is to use AppData when you install tumblrthree and you would need to change the setting in settings to use this function.

It is a bit confusing I am sure, and it gets tricky when you do an update if you have multiple instances of the program the way I do.

You can look at issue #107 to see the procedure I have been using to make use of the portable mode.
