### ISSUE TITLE
Evaluating blog sites

### ISSUE THREAD

**Issue by Linktydraa** [johanneszab/TumblThree#109]
Hi all,

Whil looking at my queue, I noticed that on a few blogs, it says "Evaluated *insert #* blog site". I don't know what this means and it's the first time I'm seeing it. What would cause this message under the crawling blog to show up?

**Comment by johanneszab** [comment]
Wanted behavior. For private blogs, which I assume you're downloading, there is no easy way to tell how how many posts a blog has. Thus, the crawler just starts at page one concurrently with several threads depending the number specified in the settings until it reaches the end. It then updates the statistics accordingly.

If you have any better idea, feel free to commit a patch.

For further questions and non-issues like this, please ask then in [Discussion and Questions](https://github.com/johanneszab/TumblThree/issues/112) and do _not_ open a new issue for that.
