### ISSUE TITLE
Terrible disk performance, fragmentation

### ISSUE THREAD

**Issue by reyaz006** [johanneszab/TumblThree#111]
After downloading few blogs, I've checked my HDD with Defraggler. The absolute most fragmented files were the files downloaded by TumblThree. One 90mb video file has >11400 fragments. Navigating downloaded folders is quite a pain, and I've even noticed that most of applications tend to work far more slower when TumblThree downloading files, even though they are not using the same HDD. That's the first time I've experienced such a thing.

The other most-fragmented file is some 800mb video downloaded through torrent, it has ~7000 fragments. That may be quite bad, but 11k fragments for 90mb file is insane.

**Comment by keokitsune** [comment]
I don’t know if its related but I have noticed that while using the program my hdd hangs or stops responding when under heavy program use like every 5-20 minutes, originally I thought it was just my crappy external hdd that was being weird, but bought an internal hdd and it has the same issue and its only when using this program that it stops responding and locks up the rest of the computer based on a second drive until a forced restart (which results in corruption of the blog file and I have to start over), most of the time I can see the Drive letter but the contents are gone, that’s when I know the hdd is not responding and the rest of the computer is about to lock up, so far every disk check program I run says everything is fine, but I do have almost 3k blogs that are constantly being crawled and scanned for duplicates. But my other archive programs and anything else I do on the hdd works fine and runs with no issue and iv even recently went through a full os reinstall so pretty sure it’s something with the program.  

I don’t know if my secondary hdd hanging and my OS hdd and programs locking up is just an extreme version of what you have nor not. Or it’s a separate issue but again my program runs almost 24/7 on a massive number of blogs.

**Comment by reyaz006** [comment]
Yes, the HDD load I see when the application is downloading files is mostly always 100%.
