### ISSUE TITLE
Star rating

### ISSUE THREAD

**Issue by tumblthreefan** [johanneszab/TumblThree#117]
Hi, is it possible to remove a rating? The yellow stars on the white background are also slightly difficult to see; could a darker colour for the stars be used instead please?

(A huuuuuuge thank you for all your hard work on this application! It's by far the best, most reliable and feature packed Tumblr downloader available!)

**Comment by johanneszab** [comment]
Thanks for the suggestion.

I've actually changed the star color once to black but that was during a testing session and it never reached the final code. I see the point. It's just changing a RGB color code ..

Unforunately, there is no easy way right now to set the star rating to zero. You could open the .tumblr data base files in the Index folder of your download location of the particular blogs in a text editor and change the Rating to 0.
