### ISSUE TITLE
Are larger files (videos) truncated?

### ISSUE THREAD

**Issue by johanneszab** [johanneszab/TumblThree#12]
Is it just me and my test blogs or are videos broken and truncated and only around <10mb size after the download? Was there any size limit for videos previously?

Someone around here who is downloading more videos than I do? I rarely use the application myself right now, so it's hard for me to detect all the issues.

Thanks for any reply.

**Comment by Jalbre2** [comment]
I don't know what changes tumblr makes to the video files after upload, as I don't back up my own blog, but when I download from other blogs, I get many long videos that are larger than 10MB. 100+MB is not uncommon.

**Comment by johanneszab** [comment]
Okay, thanks! That's good to know.

Most of the files I've looked at all seemed to have an improper ending which made me suspicious. I've thought already I've messed up the bandwidth throttling implementation, even though the pictures all seemed to okay. Bandwidth throttling turned out be much more complicated than I thought initially.
