### ISSUE TITLE
The queuelist could not be loaded

### ISSUE THREAD

**Issue by kingbode** [johanneszab/TumblThree#131]
after adding one or two blogs and adding them to the queue , then close the app and re run it , I see this error

![image](https://user-images.githubusercontent.com/26453992/29908611-767ff714-8e22-11e7-83dd-22c1b13c2827.png)

**Comment by johanneszab** [comment]
I've some doubt this really happens the way you described it. I'm sure you've read my comment to the queue in the release notes, right? 


I've just added each kind of blog for testing purpose, added them to the queue, restarted (the same version), and the queue was back.
Send me/attach the corresponding files from the _Index_ folder for the blogs where this happens.

**Comment by kingbode** [comment]
I encountered this problem in the VS environment for earlier version , and tested again with latest release ( not in VS ) and faced the same issue, not related to previously added blogs , just when I wanted to test
 with one blog added or two, attaching the index file

when I tried to go through the code in the beginning, after running the app, and add blogs, theh close the app, I got exception on close , so I added below lines to avoid exception, but it seems like save on exit, correct me if am wrong, then I said to avoid testing on VS and try your latest release and the same result happened..not saving the blogs on exit,,, I think this is the issue, as I close the app while crwling



public void ReplaceAll(IEnumerable<string> newBlogNames, IEnumerable<BlogTypes> newBlogTypes)
        {
            names.Clear();
            names.AddRange(newBlogNames);
            if (types != null)
            {
                types.Clear();   // types.Clear(); //
                types.AddRange(newBlogTypes);
            } // types.AddRange(newBlogTypes);
        }

**Comment by johanneszab** [comment]
Works for me. Newest code, newest release, no issues. Even when I close the application during an active crawl or in VS.

As I've already said, I think you're mixing old code or saved queues with new one code/saved queues, thus the blogtypes is null since they weren't saved earlier in the queue save file as I've mentioned above (and in the release notes). 

I've made [the corresponding changes](https://github.com/johanneszab/TumblThree/commit/2c522adc9b31cf95188b17dd85f5c48222702d78) on the 25th August.

**Comment by johanneszab** [comment]
Did you try deleting your settings files? I'm not sure why this would help, but apparently it helped [here](https://github.com/johanneszab/TumblThree/issues/121#issuecomment-326661473).
