### ISSUE TITLE
Images and videos not being download for newly added blogs

### ISSUE THREAD

**Issue by UltimateGTR** [johanneszab/TumblThree#140]
I'm using the latest release and seems all the images and videos are not being download when the blog is newly added, only the url lists are presented in the download folder.  The strange thing is this does not affect blog added long time ago, such as added 1 week ago, which updated fine with the latest images and videos.

After a while, I decided to test in a virtual machine, where it never run TumblThree before, and surprisingly the files are downloaded for any newly added blog!  I wonder is anything corrupted due to upgrade the tool from an older release? Or the settings file?

**Comment by Taranchuk** [comment]
I guess that you have the enabled function of downloading url lists in the details view. Uncheck this checkbox and after that the files should be downloaded normally.

**Comment by UltimateGTR** [comment]
Thanks for the reply!
My fault to change the setting to enable download url list by default since I thought this will download both contents and url list at the same time.  Sorry!
