### ISSUE TITLE
releases 8.23 and 7.30 not saving settings

### ISSUE THREAD

**Issue by tringate** [johanneszab/TumblThree#143]
After a few months of not updating to the current release, today I decided to give the current releases 8.23 and 7.30 a test drive on my trial instances.

They both download the test blogs just fine, but they both show an error when launched. error 1: The queue list could not be loaded....  error.  Neither version will save the settings.
I did remove the column settings from the settings.json file and then tried deleting the settings.jason file.  That makes no difference.  When I delete the file it does not replace it.

I run in the "portable" mode but went to the normal location in apps data and those files still have the July date on them so they are not being changed either.

I have made sure tumblr three is running in administrator mode, and made sure I clicked "YES" for it to make changes on my system.  I normally do not do that as it is not necessary, but to be safe I tried that as well.

All of my older versions work just fine and make the updates to the settings.json file with no problem.  Even the individual blog entries in the index folder do not get updated with changed settings.

It's as if the hard drive is read only, but of course it is not as the photos are saved just fine.

If I edit the files with a text editor, then the settings change in tumblr three.  I have never tried running multiple instances of the 7.x release but do want to give that a try.  My experience with release 7.x is that it is much slower than the 8.x release has been, but that could be because I have done very limited testing of the two using identical blogs lists.

I first updated the instances to the new release following my old practice of deleting all the files and then launching the new version and changing to the portable mode and resetting all of the parameters I want.  That did not work as it did not save any .json files at all in either apps data or in my portable location.  By returning the original .json files to the portable directory I could change the settings by editing the .json files so the program is looking in the right place for the files.

I did notice that when I close the new releases the cursor shows the busy spinning circle for a few seconds before going back to a normal cursor.  That does not happen on the previous releases.  So the program is trying to do something on close that is taking a long time or is failing in some way.

What am I doing wrong?

Tom

**Comment by johanneszab** [comment]
Remove your _queuelist.json_ in _C:\Users\YOURUSERNAME\AppData\Local\TumblThree\Settings\\_, after that it should work.
Then you'll probably also want to remove the _settings.json_ since I've changed the manager layout in the v1.0.8.22 release.
You could alternatively only remove the changed settings individually.

It's written in the release notes of the v1.0.8.20/v1.0.8.22 releases.

**Comment by tringate** [comment]
Thank you for the explanation.
I discovered how to fix the issue with the new information.  It is also necessary to remove the old files located in the users/AppData area EVEN if you are using portable mode. Editing them in the location the working files are in for portable mode does not stop tumblr three from still looking at the files in the AppData area apparently.  Those files were still in the old format which was causing tumblr three to not update the files in the portable area even though the files had been edited.

Your note says to edit or remove the files in the AppData area, however someone like me who uses portable mode could interpret that to mean "do it in the location of the portable files".  It might be a good idea to add a comment about in portable mode you need to do the edit or remove in both areas.

Thanks again for the help.  All is working just fine now.
