### ISSUE TITLE
Do not know why, no version can not be used, can not add blog, and the program will die 

### ISSUE THREAD

**Issue by android0221** [johanneszab/TumblThree#146]
Is the system not compatible? And there is no added blog. Is it set up or not?

**Comment by johanneszab** [comment]
What am I supposed to answer here? How would you answer your own question based on these two sentences?

Maybe you define what "the system" is and what blog you try to download. Always try at least the default settings with the newest release before opening any issue.

If you then want help, provide useful information (best would be screenshots) for others to reproduce your issue. I seriously cannot provide help based on your two sentences.
