### ISSUE TITLE
Some blogs are evaluated but no pictures are found

### ISSUE THREAD

**Issue by ErikBrown2** [johanneszab/TumblThree#147]
For some blogs TumblThree does not find any pictures. The blogs are evaluated but no images are found.  No error message is shown. When you look with a webbrowser, many pictures are shown. A sample blog where this is seen is https://kateslips.tumblr.com/

**Comment by johanneszab** [comment]
Not sure what you're doing, works for me just as fine. Default settings, no issue at all.

![kateslips](https://user-images.githubusercontent.com/1684561/31185387-17c0b78e-a92c-11e7-95fa-258c41355541.png)

**Comment by ErikBrown2** [comment]
Thanks for the reply. I found that removing these blogs and adding them again solved the issue.
