### ISSUE TITLE
[Bug?] Time limits don't work

### ISSUE THREAD

**Issue by apoapostolov** [johanneszab/TumblThree#163]
I am trying to download only new posts since 20171015 until now, in order to continue downloading blogs on a new storage. However I noticed that the application ignores time limits in format YYYYMMDD, even if set in the global settings. I use empty for end period, which should be now by default.

Downloaded files, I checked their date and time and they go past the minimum time period.

**Comment by johanneszab** [comment]
Put in both dates.

**Comment by apoapostolov** [comment]
Thank you. Apparently that works with TO set to a future date.

**Comment by johanneszab** [comment]
Thanks for sharing.

I've updated the release so that it behaves as it's described in the tool tip. One date is now sufficient and the other one will be set automatically.

**Comment by apoapostolov** [comment]
This is great, thanks for the quick support. Loving your app so much!
