### ISSUE TITLE
[Feature Request] Archive Files

### ISSUE THREAD

**Issue by WillScott73** [johanneszab/TumblThree#165]
Hi

I have limited space on the PC that I use to download Tumblr content, and I move blogs off to a removable external drive. If I do this with TumblThree the entire blog is lost from the UI. I guess that the folder structure is enumerated to determine which tumblrs we follow.

So I'd like the ability to move files/folders and not have TumblThree lose track of the blog, or worse, re-download Gb worth of files that I've already archived to another location.

**Comment by johanneszab** [comment]
It's implemented already.

Leave the database/index files named after your blog in the _Index_ folder of your download location. E.g. your blog is named _wallpaper_, then leave the _wallpaper.tumblr_ and _wallpapers_files.tumblr_ in _mydownloadlocation_\Index\.

The suffix can vary depending on what blog type you download (search, hidden, normal blog), but the root name does not.

As long as those two files stay in place, you can (re-)move any downloaded file.

**Comment by WillScott73** [comment]
Thanks. I'd not spotted the index folder, which I'd moved to the external drive. Moved it back :o)
