### ISSUE TITLE
The old raw link is broken

### ISSUE THREAD

**Issue by maxjame5432** [johanneszab/TumblThree#168]
I used the TumblThree v1.0.8.29 and when I downloaded It still download 1080 only It doesn't download raw image. So I think they changed to the new raw link again and I found code from [Userscript](https://greasyfork.org/scripts/31593-tumblr-images-to-hd-redirector) that redirect to 

> s3.amazonaws.com/data.tumblr.com/xxxxxxxxxxxxxxxxxxxxxx/tumblr_xxxxxxxxxxxxxxxx_raw.jpg

From the [#158](https://github.com/johanneszab/TumblThree/issues/158) It's good information but i think you should add more code for download raw images

I think this information is helpful for you :)

**Comment by johanneszab** [comment]
Interesting. I've just randomly tried the _data.tumblr.com_ and also your suggestion, both worked. At least the SSL certificate issue about a wrong common name would be gone if we switch to the amazon s3 host.

Do you have any example by hand where the data.tumblr.com url in fact doesn't work?

Thanks for the information!

**Comment by maxjame5432** [comment]
Can you explain the question? I don't clearly understand that.

**Comment by johanneszab** [comment]
I'm just interested in an example where only the https://s3.amazonaws.com/data.tumblr.com/ url/host works but not the previously used https://data.tumblr.com/ anymore.

But I'll check some for myself, maybe I can find one.

**Comment by maxjame5432** [comment]
it just change  no.media.tumblr.com only

#Ex.
The general link image is
> https://78.media.tumblr.com/226bcb398bfa70085190d7893192090a/tumblr_oyt5h1D0op1qa5045o2_1280.jpg

Right? And I changed after https and before end .com like this (by don't use userscript 'cause tried on smartphone)
> https://s3.amazonaws.com/data.tumblr.com/226bcb398bfa70085190d7893192090a/tumblr_oyt5h1D0op1qa5045o2_raw.jpg

Note: If use amazonaws, it used raw size only and below 1280 to smallest it can't use in this mode.

I thinks it would help you somethings

**Comment by crockpoot** [comment]
I just attempted to rip a blog and got max 1280 instead of the raw size, even though I selected raw in the settings. Am I doing something wrong? 
I know that if you change the URL of the media from this
https://XX.media.tumblr.com/XXXXXXXXXXXXXXXXXXXXX/tumblr_XXXXXXXXXXXXXXXXXXXX_1280.jpg
to this
https://data.tumblr.com/XXXXXXXXXXXXXXXXXXXXX/tumblr_XXXXXXXXXXXXXXXXXXXX_raw.jpg
it works.

**Comment by Gabriel11999** [comment]
I noticed the same issue when I used to manually try to access raw tumblr images. Does the latest version have a work around for this issue?

**Comment by johanneszab** [comment]
> I noticed the same issue when I used to manually try to access raw tumblr images.

If you noticed it, then, where is the example url I've asked for?

As I've said earlier, I think it's the exact same file, just accessible by a different host/dns. Thus, for my testing of ~50 urls, either both urls (data.tumblr.com and s3.amazonaws.com/data.tumblr.com/) worked or none of them.

And no, thats why TumblThree still uses the data.tumblr.com urls for accessing raw tumblr photo files.

**Comment by Gabriel11999** [comment]
It appears https://data.tumblr.com is using an invalid cert since its registered to s3.amazonaws.com by my AV? HTTP appears to work fine.

HTTPS:
[https://i.serealia.ca/2018/01/Cf4QGCv_2018-01-20_08-20-25.png](https://i.serealia.ca/2018/01/Cf4QGCv_2018-01-20_08-20-25.png)

HTTP:
[https://i.serealia.ca/2018/01/3Ls2Yd6_2018-01-20_08-22-42.png](https://i.serealia.ca/2018/01/3Ls2Yd6_2018-01-20_08-22-42.png)

**Comment by johanneszab** [comment]
And you are telling me this now, because..?

**Comment by Gabriel11999** [comment]
I just woke up, and took the time into looking the issue on my computer before going to work?
This Tampermonkey script uses a similar work around: [https://greasyfork.org/scripts/31873-use-tumblr-raw-image/code/Use%20Tumblr%20Raw%20Image.user.js](https://greasyfork.org/scripts/31873-use-tumblr-raw-image/code/Use%20Tumblr%20Raw%20Image.user.js). I have to leave for work now, not sure if I've actually helped at all but thanks again for making this program. It's made my life so much easier!

**Comment by Gabriel11999** [comment]
Even after removing the AV it appears to still have an invalid SSL cert. [https://i.serealia.ca/2018/01/chrome_mVbar2j_2018-01-23_00-29-00.png](https://i.serealia.ca/2018/01/chrome_mVbar2j_2018-01-23_00-29-00.png)
