### ISSUE TITLE
Files not complete and no download

### ISSUE THREAD

**Issue by ratschenrudi** [johanneszab/TumblThree#172]
Hello. 

First of all, thank you for your hard work.

Sadly i have two problems.

It seems, that TT won't download all images of a blog.
I used TumbleOne for a long time.
When i compare the downloaded Files (downloaded at the same day), the TumbleOne downloads seems complete, but TumbleThree is missing a lot of files.

I don't know why. :(

For example:

![to_2](https://user-images.githubusercontent.com/33717135/32941408-05f4dfd6-cb86-11e7-9058-04babecd87f9.PNG)
![tt3_2](https://user-images.githubusercontent.com/33717135/32941414-08f0f88c-cb86-11e7-8698-00711a5980ca.PNG)

Second problem is, that TT is scanning a blog (Queue tells Evaluated 3000 ...) and when the scanning is finished no file was downloaded.
I'm autheticated to the tumblr network and no error message is displayed.

Thank you very much in advance for your help.

**Comment by johanneszab** [comment]
Can you also check the box _Download reblogged posts_? I guess that will already fix your problem, otherwise I'll take a look later today.

Most posts from people on Tumblr aren't orignally from their selves, but re-blogged from someone else. Thus, if you do not enable that box, only the pictures the author has uploaded him/herself will be downloaded.

**Comment by ratschenrudi** [comment]
Thank you for your fast reply.
Ah, ok. 
I thought _reblogged posts_ are text posts, not images.
My fault.

I see, that there is no hint on that option like the others (Skip .gif files, too. Version 1.0.8.31)

I will test with that option checked.

**Comment by ratschenrudi** [comment]
Perfect. That did the trick.
Works like a charm.
Thanks. 👍 

Maybe it's possible to add a new column _Downloaded Images_ to the main window?
That would be create. :)
