### ISSUE TITLE
global database and blogs no longer in the blog list?

### ISSUE THREAD

**Issue by keokitsune** [johanneszab/TumblThree#182]
i constantly add and remove blogs, mostly when a blog goes offline, with the new global database i was wondering if i save a copy of the _files file and then remove the offline blog and re add the _files does the crawler still look at and consider that content when the connecting blog is no longer acticly part of the blog/crawl list? and if not is there some way to make one large reference list located somewere other then the blogs folder, so the already downloaded blogs info can persist even when a blog is removed, i would think it would also help with redundency, insted of 50 blogs lists with the same content info there would just be one.

**Comment by johanneszab** [comment]
* All \*_files.\* from the _Download Location_ (Settings-General) are loaded into memory during startup.
* If you add a blog, those files will be added to the in-memory-global database.
* If you remove a blog in TumblThree, those files will be removed from the in-memory-global database.
* If you put a random _files.tumblr in the _Download Location_ with filenames in the _Links_ array you don't want to download again before starting TumblThree, those filenames will be checked even if there is no corresponding .tumblr in the index folder.
