### ISSUE TITLE
[Feature Request] Additional Video Download Sources

### ISSUE THREAD

**Issue by flaccidbagel** [johanneszab/TumblThree#183]
First off, just wanted to say thank you for your work on this program. Its definitely saved me a massive amount of time backing up Tumblr content.

I'd like to request additional sources for video downloads, if at all possible.

Currently, we can download from imgur, gfycat, and webmshare automatically. Are there any plans to add additional hosts to that list, such as Vimeo, Google Drive Video Links, or Mixtape.moe? 

Thanks again.

**Comment by johanneszab** [comment]
Could you share some example tumblrs using those services?

**Comment by flaccidbagel** [comment]
I made a quick blog myself that tried to showcase the above hosts. There's a post with an embedded Vimeo video, two posts linking to a webm hosted on Mixtape.moe, and lastly, that same Webm hosted on google drive, posted 3 different ways: Once as a link in a text post, once as a link type post, and lastly as a text link in the description of an image post.

I hope that helps, and thanks again for your work.

**Comment by flaccidbagel** [comment]
https://ithinkimhelping.tumblr.com/

I made a quick blog myself that tried to showcase the above hosts. There's a post with an embedded Vimeo video, two posts linking to a webm hosted on Mixtape.moe, and lastly, that same Webm hosted on google drive, posted 3 different ways: Once as a link in a text post, once as a link type post, and lastly as a text link in the description of an image post.

I hope that helps, and thanks again for your work.
