### ISSUE TITLE
[Feature Request] Show Confirmation When Removing a Blog

### ISSUE THREAD

**Issue by WillScott73** [johanneszab/TumblThree#186]
I hadn't noticed that I'd selected multiple blogs when I chose Remove Blog. All blogs were removed and although the images.txt and videos.txt files exist, now that I've re-added the blogs all files are being downloaded even those previously downloaded. This may be because the previous downloads have been archived to an external drive though.

**Comment by johanneszab** [comment]
Duplicate of #130, #98.
