### ISSUE TITLE
新用户 无法添加博客 

### ISSUE THREAD

**Issue by jeasonnnn** [johanneszab/TumblThree#189]

**Comment by johanneszab** [comment]
Thanks for making be aware and sharing the url.

It was indeed broken once I'd finished the rewrite of the url detector two weeks ago. I actually forgot to test the "add blog"-text field in the gui separately as I'm always using the clipboard monitor. They share 95% of the code, but that obviously didn't help.

Someone else mentioned [this here already](https://github.com/johanneszab/TumblThree/issues/184).
