### ISSUE TITLE
Randomly not scanning images?

### ISSUE THREAD

**Issue by blezinski** [johanneszab/TumblThree#19]
i just noticed the program just goes blind randomly and wont see any new content unless i delete the blog and re-add it. anyone else had that issue?

edit: it's like everytime i update the program all the blogs i added prior go invisible

**Comment by johanneszab** [comment]
> edit: it's like everytime i update the program all the blogs i added prior go invisible

It never happened to me so I cannot fix it. Send me one of the now invisible .tumblr files from the Index folder of your download location and maybe also your Settings.xml in the Appdata\Local\TumblThree folder of your user.

**Comment by blezinski** [comment]
i reckon i figured it out, all the blogs i had saved showed twice as many files downloaded vs how many there was on disk and re-addng them reset the count

**Comment by johanneszab** [comment]
Readding? How? What exactly did you do? 

Do you store the same .tumblr file twice in the same folder, just renamed?

**Comment by blezinski** [comment]
i reinstalled windows a couple months ago and all my blog downloaded file counts doubled, the same day all the blogs went invisible. i guess deleting the appdata folder made the program shit itself
i havent messed with any of the .tumblr files
