### ISSUE TITLE
Entry point not found

### ISSUE THREAD

**Issue by Raynor69** [johanneszab/TumblThree#190]
When opening the exe this error comes up
"the procedure entry_strtoui64 could not be located in the dynamic link libary
c:\windows\system32\d3dcompiler_47.dll"
Windows 10 pro 64bit latest updates.
![error](https://user-images.githubusercontent.com/5622406/34673099-58c26eb4-f43e-11e7-99c6-20fca5ef3c20.jpg)

**Comment by johanneszab** [comment]
I think this is not a TumblThree issue, but probably something with your installation. That .dll is clearly from Microsoft, nor did I write any function that converts strings to uint64 (thus it must be a part of .NET) and if you extracted TumblThree as described on the web page, it's working with Windows 10 pro 64 bit latest updates:

![windows10_1709](https://user-images.githubusercontent.com/1684561/34674220-526b3ad6-f485-11e7-8417-f40eb922734d.png)

How exactly did you install/extract TumblThree? Maybe you should [google for the error message](https://answers.microsoft.com/en-us/windows/forum/windows_vista-performance/the-procedure-entry-point-could-not-be-located-in/a02c08f7-b717-4dba-a596-355012aa000d?auth=1)?
