### ISSUE TITLE
[Bug] On hidden blogs does not work the function of downloading posts by the pages and they are completely scanned from beginning to end during repeated crawling

### ISSUE THREAD

**Issue by Taranchuk** [johanneszab/TumblThree#191]
On hidden blogs does not work the function of downloading posts by the pages, when I set the number for example 1-3 last pages for downloading, then the program downloads blogs completely, not just the last 3 pages. Also when the downloading of the hidden blogs ends and I put them in the queue panel again, then the program starts to scan them completely from the beginning to the end and does not crawling only the last posts (for example 250 last posts as is the case with regular blogs). It would be great if you could fix it or implement it if it is not already implemented. Thanks!
P.S. Originally my comment was on another topic, but I deleted it because it was offtopic and decided to create a separate topic.

**Comment by johanneszab** [comment]
It's not even implemented. I must have added the textboxes while implementing the different detail views for each downloader without explicitly checking the TumblrHiddenCrawler.cs class for its capabilities. Usually I try to implement everything in both at once.
It's probably just a few lines of code or even the exact same as for the TumblrBlogCrawler.cs.
