### ISSUE TITLE
How to use TumblThree with Shadowsocks

### ISSUE THREAD

**Issue by se9099** [johanneszab/TumblThree#192]
系统是WIN10 64位的 下载的几个中文版 1.0.8.33 1.0.8.32 1.0.8.36 复制网址点添加博客没有任何反应 英文版试过39的 也是一样 求解决 谢谢

**Comment by se9099** [comment]
![image](https://user-images.githubusercontent.com/35278301/34748723-dcb1c88c-f5d8-11e7-8426-c5056dd7f50d.png)

**Comment by johanneszab** [comment]
For me adding the same blog in v1.0.8.39 actually works:
![kuurakuu](https://user-images.githubusercontent.com/1684561/34759743-40c2db32-f5dd-11e7-96ba-a0ec14b40f10.png)

Does your download location exist (i.e. the folder/device is connected)?

**Comment by se9099** [comment]
添加博客的按钮可以点击 不过点击完之后就没有反应了 我是中国的 需要挂shadowsocks 才能访问  挂shadowsocks直接访问网页一切正常  是不是tmblthree 也需要进行设置？

**Comment by se9099** [comment]
![qq 20180112081744](https://user-images.githubusercontent.com/35278301/34853982-c25099d8-f771-11e7-8b83-ae321e012743.png)系统我刚做完

**Comment by johanneszab** [comment]
Yes, if you're behind a proxy/VPN, you'll have to set it up.

It only takes http proxies and it can be either entered like

    IP Port e.g. 35.23.6.1 80

or

    http://host Post e.g. http://myproxy 8080

I think. So the IP is without a leading _http://_ in my short tests. Someone here already had issue on how to enter the value. Take a look at these: 181, 91.

Also maybe you can cross post here: https://github.com/Emphasia/TumblThree-zh as I don't have any experience with shadowsocks, but apparently there are other Chinese users. If you figure it out, letting us know here on how you did it would be very nice.
