### ISSUE TITLE
Download Wildcards

### ISSUE THREAD

**Issue by bun-dev** [johanneszab/TumblThree#199]
![sc](https://user-images.githubusercontent.com/34141271/34914061-bc3208c0-f8d9-11e7-88d0-55b61dba536f.png)

For future site parsers(webmshare,etc), allow a wildcard selector so that any file format from that site can be downloaded.

**Comment by Taranchuk** [comment]
It would be nice to extend this function so that all direct links from any sites could be downloaded. Just add one more item "Download files by any direct links."

**Comment by bun-dev** [comment]
That's a good idea. I'll try and see if I can include a method like that.
