### ISSUE TITLE
App doesn't work, it doesn't DL

### ISSUE THREAD

**Issue by EC-O-DE** [johanneszab/TumblThree#200]
I have tried the two latest in the releases section.. If I add blogs the app does though find the amount of total posts, but nothing happens when crawl clicked.

Maybe I need a "clean install"...

**Comment by johanneszab** [comment]
So, I'm not really sure what I'm supposed to answer here? There isn't that much information in the two sentence, and downloading, even with old blogs, works for me in the .39 release.

So, I start guessing: Are you using the global database feature? It has to load all the databases into memory before the crawl starts. That shouldn't take much time, but how many blogs do you have in TumblThree? The crawl will start (green bar) after that. Please try that with the **.39** release. The .36 has a bug that if you change anything in the settings, you'll have to restart TumblThree afterwards if you want to crawl (except you also change the download location or the "global database"-option or both). I forgot that there is a possibility to change none of them while opening the settings and then the crawler waits for a "okay, databases are loaded", but that never happens .....
