### ISSUE TITLE
Total Number of Liked Posts Not Downloading

### ISSUE THREAD

**Issue by c5001481Cepheus** [johanneszab/TumblThree#202]
Hi! Not certain if this is a bug, could very well be an option I'm overlooking, but crawling the likes on a blog (e.g. http://www.tumblr.com/liked/by/exampleblogname) for download, only downloads a small amount of them (about 700). The liked posts are over 10,000, and the number downloaded was about 700. The status bar is full which signifies the downloading is complete. Am I missing something?

**Comment by johanneszab** [comment]
Did you read the instructions in the [README](https://github.com/johanneszab/TumblThree#application-usage)/[on the website](https://www.jzab.de/content/tumblthree#usage)? Did you get any error about connection timeouts in the crawler? If yes, the crawl is incomplete and you'll have to requeue it.

I've tested it with a blog with 37'596 likes, where TumblThree downloaded 34'053 likes and said there were 2'446 duplicates, which comes pretty close to the total number, assuming there are really only photos and videos.

Thus, I'm guessing you're doing something wrong. But like I've already said here countless times before and before (e. g. #177): Without the url you're trying to download, there is nothing I can possible do. Thus, either read the instructions (which took me time to write), or do not open an issue without a proper way to reproduce your issue!

**Comment by c5001481Cepheus** [comment]
Thanks for the reply! I've just now read the readme. I'm very new to Github and didn't notice the file list, The download appears to be working now. Thank you for your assistance and your work on this great program!
