### ISSUE TITLE
软件添加博客无响应

### ISSUE THREAD

**Issue by zockparty** [johanneszab/TumblThree#203]
一共试用了四次，第一次在Windows 7 环境使用.36版本，添加博客成功，在未翻墙的情况下成功下载部分文件，中途显示连接超时关闭，然后停止下载重新启动就无法下载，关闭重开也没有解决，删除博客尝试重新添加，点击添加按钮后无显示，但是点击开始按钮能够生成对应博客文件夹，只是没有任何下载记录；第二次在Windows 10环境使用.36版本，直接出现博客添加无显示，点击开始按钮能够生成对应博客文件夹，无下载记录；第三次在Windows 7 环境使用.39版本，与第二次情况一致；第四次在Windows 10 环境使用.39版本，与第二次情况一致。
问题：1.是否需要安装其他基础软件，或者进行相关设置？目前总是出现添加博客不显示的问题；
2.是否需要翻墙，或是有其他影响因素需要考虑？

**Comment by johanneszab** [comment]
@Emphasia: If you can say anything about this :smile:. You're the only person here I know of that can understand Chinese, thus might live in China and uses TumblThree.

I'm thinking it has something to do with the great firewall in China, thus one will have to setup the 'HTTP Proxy' in the 'Settings' of TumblThree. I've tested the setting [here](https://github.com/johanneszab/TumblThree/issues/181) and they seemed to work. Since I cannot test this behind the Chinese great firewall, I cannot really answer this question. Thus, I'm guessing it might even be related to #192.

**Comment by zockparty** [comment]
@johanneszab Sorry，I repeat it in English.
I've tried 4 times. The first time was in the Windows 7 with .36 version,  I added a blog and downloaded  some files successfully without cross the firewall.  Then it shows connection timeout  halfway, and  I stop the downloading and restart the task ,but it can not download anything this time. Then I shut down and restart the software ,the problem was still there. Then I delete the blog task and try to re-add it, after I click the Add button ,there's nothing display, but if I click the Start button it will generate the corresponding blog folder with blank download record. 
The second time was in the Windows 10 with .36 version, the problem shows directly as the first time.
The third time was in the Windows 7 with .39 version, after I overwrite the original file with the new version , it shows the blog task the first time ,then shows the same problem after I restart the software.
The last time was in the Windows 10  with .39 version, same with the second time.
Questions: 1. Do I need to install other basic software, or related settings? 
2. Do I need to cross the firewall or other factors to consider?

**Comment by Emphasia** [comment]
翻墙的确是需要的。挂代理或者改hosts（只要能保证网页版能正常访问，同时TumblThree代理设置和浏览器相同）都可行。

@johanneszab I've mentioned the need for proxy in README, but it may not be obvious enough that people always ignore. I'll highlight it on the release page, maybe that'll help a little.

**Comment by johanneszab** [comment]
So, it's straight forward to use that anyone can do, or do you need a complicated hack for this? I'm guessing it's not different compared to the situation here when I would use a proxy, right? 
Just search (maybe pay) for something in the internet..?

**Comment by Emphasia** [comment]
@johanneszab Yes, TumblThree itself is not the problem, the GFW is. As long as one can access the WEB tumblr.com, TumblThree will function just fine. As for finding an available Proxy that is not the problem that TumblThree needs to solve.

**Comment by johanneszab** [comment]
Okay, thank you very much.

I think I'll close this then, and also #192.

**Comment by ky0ncheng** [comment]
@Emphasia 没找到代理设定的位置

**Comment by Emphasia** [comment]
@ky0ncheng 软件中已经没了 在IE中设置全局代理就行
