### ISSUE TITLE
downloading raw image files no longer works

### ISSUE THREAD

**Issue by anim240** [johanneszab/TumblThree#205]
a while ago the path to accessing them had changed where you also have to turn '78.media' to 'data' instead of just 1280 to raw, ever since then 1280 was all I could get while batch downloading

**Comment by johanneszab** [comment]
Please check the old issues before opening a new issue.

That's already covered in multiple issues (#158, #168) and the [code was changed reflecting exactly what you mentioned on 13. Oct 2017, 4 months ago](https://github.com/johanneszab/TumblThree/commit/81af40ca0719f6315d1dedc4e18aa63d7272d97e).

**Comment by johanneszab** [comment]
For me it works. If you can download _raw files depends on the age of the file you're downloading. _raw files do not exist for all images. It's covered somewhere in the issues.

You might want to delete your settings, that maybe updates your host list. I'm sure I have had this mentioned in the release notes. But in pinciple, it **does** work
