### ISSUE TITLE
Bloglist empty after Crash of OS

### ISSUE THREAD

**Issue by Kvothe1970** [johanneszab/TumblThree#206]
After an OS crash and system restore, my blog list is empty. I do have backup of the "index" folder and have restored that from my online backup from last night. However, the blog list is still empty. Is there a way to restore my bloglist? Which files are needed? (Note, I did not in fact, back up %APPDATA%/local I am afraid.

**Comment by johanneszab** [comment]
Your download location actually still points to the right directory? Otherwise there would be error popping up in the GUI if the blog indexes in fact were damaged.

**Comment by Kvothe1970** [comment]
That was it. Thank you kindly. 
I am still trying to sort out what happened but it seems that this also wiped the config.

Is there anything else I should include in my backup  from now on?

**Comment by johanneszab** [comment]
In %localappdata%\TumblThree are just the settings and the queue list stored. The more important things are indeed the blog indices.

There is nothing in the registry whatsoever.

**Comment by Kvothe1970** [comment]
Perfect. I’m glad it was so easily resolved. 
Now off to analyse the windows event log :)
