### ISSUE TITLE
Not Downloading Media

### ISSUE THREAD

**Issue by Kuroo2021** [johanneszab/TumblThree#207]
I download a fresh version (TumblThree-v1.0.8.39-Application) and just put one URL in the field and downloaded an archive it just zip through the blog. Now I go check the files in the folder and it only has 259 files but only three text docs in the archive without any pictures or videos. Bug?
![capture](https://user-images.githubusercontent.com/18900059/36073754-f58a1ff0-0f03-11e8-910e-69e178e04ba6.JPG)

I'm sign in through the software so it does have my account information if the blog was hidden which is it not.

**Comment by johanneszab** [comment]
> Bug?

Probably not. Without the URL of your blog it's hard to tell from your description. If it's not #194, then I'd say you did something wrong.

Post the url, so I can check on my side, otherwise be more descriptive.
