### ISSUE TITLE
Tumblr asking to login to download even though already authenticated

### ISSUE THREAD

**Issue by Linktydraa** [johanneszab/TumblThree#210]
Hello,

Tumblthree keeps telling me that I need to sign in to download some blogs, but I've signed in and authenticated on the tumblthree many times. The popup window immediately disappears each time I do it. I've turned safe mode off and done everything I can think of. Yet each time I go to download the blog, it says I need to sign in.

**Comment by johanneszab** [comment]
Remove your internet explorer cookies and do the authentication again as described in #180.

If that does not help, post the url of an example blog.

**Comment by Linktydraa** [comment]
hi Johannes,

I did the IE Cache and cookie delete and authenticated again. The window simply vanished as if it's already authenticated, and did not work.

I would pot the blog site, but it's ver nsfw
