### ISSUE TITLE
Queue isn't being processed

### ISSUE THREAD

**Issue by username13459** [johanneszab/TumblThree#215]
I've tried on an older version, and the newest version (from 2 days ago).  I can add things to the queue and click 'crawl', but nothing happens.  I've authenticated and everything.  Error occurs on blogs with and without passwords.

**Comment by johanneszab** [comment]
Default settings? What shows the queue? Any progress text below the queued blog or a green bar next to the blog in the queue? What blog?

Post screenshots, or be more verbose, otherwise I cannot help.

**Comment by username13459** [comment]
Default settings, affects every blog I've tried.  No additional information appears next to the queue.  Tumblr staff blog used as a test-blog: 
![image](https://user-images.githubusercontent.com/36827093/37051298-07ac219a-2144-11e8-80fb-3b12e3955c5e.png)

**Comment by johanneszab** [comment]
![staff_tumblr](https://user-images.githubusercontent.com/1684561/37054810-3628f426-2180-11e8-9819-90545a727cca.png)

Maybe not a 2x2 px screenshot?

Default settings, same blog, same time, works without issue. Thus, it must be something with your system. When you can even add the blog, it's not a connection issue.

**Comment by username13459** [comment]
Same settings, new install, no dice.  Any recommendations on how to continue?
