### ISSUE TITLE
Allow downloading of a specific list of tumblr posts, not just whole blogs

### ISSUE THREAD

**Issue by reversebreak** [johanneszab/TumblThree#218]
I have a thousand-strong list of specific tumblr post URLs, and unfortunately the current structure is only oriented to downloading entire blogs at once (or designated slices of those blogs, or search slices of tumblr as a whole).

I'd love to be able to feed the program a text file and have it get all the posts in that list.  This could be piped, a command-line argument, or an UI element.

**Comment by Hrxn** [comment]
Do you mind using CLI programs?

**Comment by reversebreak** [comment]
I'd be happy to use a command-line program.

**Comment by Hrxn** [comment]
Then I'd recommend [gallery-dl](https://github.com/mikf/gallery-dl). (Python, CLI, cross-platform)

[Supports](https://github.com/mikf/gallery-dl/blob/master/docs/supportedsites.rst) Tumblr, among other sites, including Likes, Posts, Tag-Searches in addition to whole profiles.

And you can take your list of URLs to Tumblr posts and use it like this:
`-i, --input-file FILE     Download URLs found in FILE ('-' for stdin)`

**Comment by johanneszab** [comment]
I'm not sure if this really fits into TumblThree though. It's nice you've found an alternative that seems to suit your needs.
