### ISSUE TITLE
How to keep images from one post close to each other?

### ISSUE THREAD

**Issue by Norithiel** [johanneszab/TumblThree#22]
How to make images to be saved in particular order of reblog? I use sorting pics by date/date modified. If i am downloading a blog with more than one images in post , these images can't be downloaded by particular order , they're just saved randomly among other images. 

For example, there is 20 tumblr posts. Program starts to save pics from these posts and it looks like at first it downloads one pic from 1st post, then three pics from 5th post, then pic from 20th post, then another one pic from 1st post. I can't make the program download them like whole 1st post, then whole 2nd etc.

I have to use TumblOne because of it lol, but it have outdated indexing system (if I delete needless pictures, and then crawl blog, TumblOne will download them again). I tried to set 1 or 2 parallel connections instead of original 25, but in that case images just are not downloaded at all.

What should I do?

**Comment by johanneszab** [comment]
Try it again with the newest binary (v1.0.4.16) and set the _scan connections_ in the Settings Window to 1. That might work, the scan is sequential then, but I later cast the (ordered) list into a hashset for removing duplicates which probably messes up the order.

In short: It's not possible (yet).
