### ISSUE TITLE
How to setting http proxy?

### ISSUE THREAD

**Issue by ky0ncheng** [johanneszab/TumblThree#220]
Version
![](https://i.imgur.com/WRD2PoC.png)

Settings UI, I can't find somewhere to set http ip and port.

![](https://i.imgur.com/Ue6rCKY.png)

![](https://i.imgur.com/i1k22eL.png)

![](https://i.imgur.com/jIyJCkt.png)

![](https://i.imgur.com/Tw9E6pj.png)

**Comment by johanneszab** [comment]
Check the release notes to the version you are using. Also the readme was updated already.

All you have to set now is the Windows proxy/IE proxy settings, nothing in TumblThree itself.
