### ISSUE TITLE
Save state/last post id in hidden tumblr crawls if performed successfully

### ISSUE THREAD

**Issue by Kvothe1970** [johanneszab/TumblThree#225]
After having run a complete check over all blogs in my last night. I just started crawling again 
I have added two non-hidden and four hidden blogs. 

The non-hidden blogs are crawled normally und TumblThree stops after having reached the point where it left off. 

The hidden blogs are crawled all over again every single time. 

Settings is back to 50 pots per page for these blogs
Force Rescan ist aus
Lade die angegeben Größen ist an
Lade reblogged Einträge ist aus
Filter via Tag is aktiv

Example from blog file: 
"ForceRescan": false,
  "ForceSize": true,
  "GfycatType": 0,
  "LastCompleteCrawl": "\/Date(1524165873754+0200)\/",
  "LastDownloadedPhoto": null,
  "LastDownloadedVideo": null,
  "LastId": 0,
  "Links": [ ],
  "LoadError": null,

General Settings:

Gleichzeitig geöffnete Verbindungen: 10
Scan Verbindungen 4
API Limit Verbindungsanzahl 100 Zeitintervall 60

Please let me know if you need to me to provide info from the index file

**Comment by johanneszab** [comment]
That's nothing new though. There is code at all in the hidden Tumblr crawler to save it's post ID if the crawl is completed successfully so that any subsequently performed crawl can pickup at that point. I've written that [here](https://github.com/johanneszab/TumblThree/issues/217#issuecomment-377131561) previously.

**Comment by Kvothe1970** [comment]
Ah okay. I probably didn't notice in the past months when the crawling stopped (which is now resolved) and hence the crawling of 120000 posts every time is much more noticeable on these blogs.
