### ISSUE TITLE
Possible Usage issue

### ISSUE THREAD

**Issue by bubbagump2** [johanneszab/TumblThree#226]
I'm running in portable mode. I have the paths set as below. I read somewhere that I can download to one location, then move the pix, vids, ect to a storage area and T3 will still keep track of the blogs and what was already downloaded.

I moved the folders from the datapath to save space, I closed the app and reopened it, there are no forums listed. I moved some of the folders back, thinking T3 would pick up on these forums again, but restarted the app, still my forum list is empty in the app.

It looks like the app looks at the folder list in the data directory and not some index/status file for a list of what forums to load....I'm sure I made a mistake or 

How do I restore the forums back to the app
How would I move "full folders" to store away, yet still keep a record of all forums and their scan/download status`

apppath = C:\Users\bubbagump\Documents\TumblThree-v1.0.8.48-Application\TumblThree
datapath = C:\Users\bubbagump\Documents\TP

**Comment by johanneszab** [comment]
Hi,

In your datapath was a folder called "Index" that contains the databases for each blog/search/likes you were downloading.

If you move that folder back to the datapath (e.g. C:\Users\bubbagump\Documents\TP\Index) and then open TumblThree, it will recognize all your previous downloads.
