### ISSUE TITLE
Unable to download using latest v1.0.4.16 

### ISSUE THREAD

**Issue by hemant-mahant** [johanneszab/TumblThree#23]
Hi
I am trying to download using the latest 1.0.4.16 (English version)
It shows all the images processing/downloading in the Queue section, but neither are actually being downloaded. Also nothing is being shown in the preview section. (Preview is on from setting)

for example :: http://senaruna.tumblr.com/

please see to it.
Thanks for the nice app.

**Comment by johanneszab** [comment]
That particular blog works for me here. So I need more information and it's most likely something with your settings.

Did you enable the downloads in the details windows? Whats your Limit Bandwidth value, parallel connections, parallel blogs and finally download location set to?

**Comment by mrbaokuo** [comment]
I had the same problem.
maybe something went wrong, all of sudden ,all blog downloading became like this.
excatly same as hamant-mahant. 
u can see the downloading process and whats being downloaded at the moment, but the download status bar is empty, no amount of files at all. 
open the blog download folder, its also empty. 
videos bacame an txt file name"video.txt".
if u look at detail section, no preview ,coz all the files are detected (number of files) but 0 is downloaded.

**Comment by johanneszab** [comment]
I'm personally thinking it's still the integer overflow as in issue #20. I wasn't really happy with the last fix since it fixes at the wrong place. Maybe I've also overlooked something somewhere.

I thought the new default values would be worth releasing a newer version for newcomers since they should not run into this issue then.

I won't have time for a proper fix and rethink everything right now, so I'll probably not fix this until end of February.

Could you both try a much smaller value for the Limit Bandwidth (kb/s) setting as in the older releases? Something below 2 million? The new default for the Limit Bandwidth is 102400 kb/s which is equally to 100mb/s.

If this resolves anything, than it's still the same thing. Thanks for testing!

**Comment by hemant-mahant** [comment]
Thanks for the quick reply. Lowering the Limit Bandwidth did work for me. Thanks.

An unrelated question. I prefer to download a lot of blogs, which almost downloads duplicate images (from different blogs). Is there any way to avoid that ?
Presently I use 'Similar Images' to deleted duplicate images, but once those images are deleted from the blog folders, TumblThree download them again on next run.

Is there any way to rectify my little problem ? Please do reply.
Thanks you.

**Comment by hemant-mahant** [comment]
Thanks for the quick reply. Lowering the Limit Bandwidth did work for me. Thanks.

**Comment by hemant-mahant** [comment]
An unrelated question I need help with.
Long ago I stared using TumblOne, and I have downloaded hundreds of blogs. Unfortunately most of images were duplicates over several blogs. So I used 'Similar Images' to find those duplicate images. And then replaced them with 0 KB null file of same names.
Now I can't use old index files of TumblOne with TumblThree, so I added each blogs manually.
But now I don't know whether previously downloaded images will be downloaded again or they will be skipped. (cause 0 KB file of same name already exist)

Also, if I accidently deleted some images, how would I download only those, when new index files won't allow it?

I know it's a messy situation, but please guide me some way out of it. Cause I have over 6 million images. ;(

**Comment by johanneszab** [comment]
TumblThree will download everything again, but you can (re)move any downloaded images from your disk as long as you keep the index file (the blog.tumblr) in the _Index_ folder of your _download location_.

In the new index files there is a list of downloaded urls to prevent a re-download. It's quite skewed already and I'm going to update this list in a future release to only contain the filenames as it simplifies things and make a list for each type of post. Right now it's just a big list. This list should then only be loaded if the blog is actively downloaded to reduce the memory usage for people that have multiple large blogs loaded. Right now, for every blog any url ever downloaded is in the memory.

It should be possible to write a small function that reads in your downloaded files and add them to the list. Would be quite simple I think, but there is nothing there yet. I've never implemented this as there is already enough other things to do and this wasn't really my priority. 

So either wait, implement it, or redownload everything. TumblThree should download quicker as TumblOne one loads one post/image per time.

**Comment by Taranchuk** [comment]
>  I'm going to update this list in a future release to only contain the filenames as it simplifies things and make a list for each type of post. 

If I have files with renamed filenames that will happen to them? This files will be re-downloaded with the old names or they will be ignored? Or the program will download again the same files and they will be in a folder with the same older renamed file?

**Comment by johanneszab** [comment]
Duplicate of #20.

**Comment by johanneszab** [comment]
> If I have files with renamed filenames that will happen to them? This files will be re-downloaded with the old names or they will be ignored? Or the program will download again the same files and they will be in a folder with the same older renamed files?

They will still be ignored since the original filename within the url is saved. It doesn't matter how you name the files on the disk.

**Comment by Taranchuk** [comment]
johanneszab, but you wrote that you are going to update the index files in a future release so that they will contain only the names of the files, not URLs.

**Comment by hemant-mahant** [comment]
hi.
Say I accidently deleted some images. And they are listed in the index files, so they won't get downloaded again. So how could I download them again ?
Will deleting the url from index file will work ? Using Notepad++.
Or will it just corrupt the index file ?
Any other way to edit index files?

Also, since you mentioned that next updates will only hold the files name instead of complete url, could you make a app seperately just to create a index files ? Like it will scan the folder for pre-existing / pre-downloaded files, and add them to index files, so that they will be skipped from downloading.

Please do reply. Cause I am on metered network & as I mentioned I have 0.8 Million images and I don't want to re-download them.
Thanks

**Comment by johanneszab** [comment]
> johanneszab, but you wrote that you are going to update the index files in a future release so that they will contain only the names of the files, not URLs.

The filename is part of the url. I just need to cut he proper parts out and distribute the big list into smaller ones.

It's easier to update the database once instead of writing and executing the code for every downloaded file and file type. The files are hosted on different mirrors for sure now, so saving the whole url doesn't make sense anymore.

**Comment by hemant-mahant** [comment]
hey, you didn't reply whether editing the index file on Notepad++ will help or not.
Also I can't simply add the downloaded files on my own, cause I don't know the complete url, but rather only the file name. And as of now, TumblThree saves complete url, so I guess adding just the files name won't help.

**Comment by Taranchuk** [comment]
johanneszab, it means the index file will check for the presence names of files in urls, that the program receives from the server, but do not check the folders for the presence of these files ... Thanks for the answer!

**Comment by johanneszab** [comment]
> johanneszab, it means the index file will check for the presence names of files in urls, that the program receives from the server, but do not check the folders for the presence of these files

Yap. I did that because the lookup of a filename of a fast in memory structure is significant faster than checking the contents of a single directory with several ten/hundred thousands of files.

It also allows to move the files to a different place after a successful download without having them to be reloaded.
