### ISSUE TITLE
New Tumblr ToS changes for GDPR break normal tumblr blog downloads.

### ISSUE THREAD

**Issue by maxcook** [johanneszab/TumblThree#234]
![image](https://user-images.githubusercontent.com/5160346/40478942-af415986-5f4a-11e8-9c49-0f7e3f9ee2b4.png)

**Comment by stuwm** [comment]
![image](https://user-images.githubusercontent.com/39588675/40482047-acc63c2c-5f53-11e8-8fa5-32872e521605.png)
Seems to be an decoding issue for all non-hidden tumblrs.

**Comment by FatKiwi** [comment]
Same here, on all blogs.

**Comment by johanneszab** [comment]
Just crawled 100 000 posts of four different hidden tumblrs, no issues. Latest version.

Please, if you report anything, write more than one sentence and describe the problem @maxcook. Just posting that image doesn't say anything. Next time I'll just close this issue. Especially if there already is an issue (#217) covering why this message is displayed.

So, any more information? Can you wipe your cookies, the settings and re-add a blog that didn't work for you on the latest version and re-test it?

**Comment by stuwm** [comment]
Sorry, I don't see any screenshots in #217 that would have told me that this is a dupe. And why did everything work yesterday, but not today, less than 24 hours later?

**Comment by FatKiwi** [comment]
Hidden ones work fine. The normal ones are being redirected to ToS confirmation.

**Comment by johanneszab** [comment]
> Hidden ones work fine. The normal ones are being redirected to ToS confirmation.

Thanks. Thats broken for me too today. Then it's the _non_ hidden tumblrs. I've only tested hidden tumblr as mentioned above.

**Comment by johanneszab** [comment]
Okay, it's already working when I add the cookie we generate by agreeing to the new ToS that is used in the tumblr search and hidden tumblr crawlers to the requests we use for normal blog downloads.

I'll fix this later today and also add the cookie to the tag search crawler. Hopefully they are done changing things now as it's already the 25th of May (GDPR deadline).
