### ISSUE TITLE
download stops before end : Limit exceeded

### ISSUE THREAD

**Issue by amorakfd** [johanneszab/TumblThree#235]
Latest release of Tumbl3 now adds correctly blogs to list but downloading stops before end of crawl MSG : Limit exceeded : You should lower the connections to the tumblr api in the settings- i tried many ways but still the download didn't start again. Thanks for help

**Comment by Hrxn** [comment]
This is probably expected, there are limitations in place for accessing the API, this holds true for basically all sites or services.
