### ISSUE TITLE
inline images?

### ISSUE THREAD

**Issue by blezinski** [johanneszab/TumblThree#24]
i know i had a thread about inline images before and you implemented downloading them, but it looks like the program downloads inline pics from some blogs but not others
re-adding the blog doesnt work
i notice the program sees everything and sets the number of downloads to one value, then i add the blog to the queue and crawl it and suddenly the number of images drops

**Comment by johanneszab** [comment]
You can add that if you need it now. It's currently only looking in regular/text posts for inline images. No quotes, no conversations or other type of posts. I wasn't sure how these work when I've implemented that.

I certainly won't add anything until I've spare time to properly code and test things. The last commits were prove enough for me to not doing it any other way.
