### ISSUE TITLE
Currently, some hidden tumblr might fail to download.

### ISSUE THREAD

**Issue by Kvothe1970** [johanneszab/TumblThree#240]
I just re-added a blog that I used to have in in my list. Files for that blog were deleted from "index" folder. Immediately after adding that blog, the message about a post not being parsable shows up. 

When I add that blog to the queue, it stalls. No progress. Setting the number to 1, does not help either. There is no progress at all of a sudden. 

Closed app again, deleted both files from the Index folder. Added again, same result. 
Deleted all IE cookies / temp files. 
Started app, signed into tumblr again. 
Closed app. 
Started again, added blog anew, immediately the same message

1. It is a hidden blog
2. Other existing hidden blogs work fine

This could just be one of those cases where the current implementation cannot proceed, just bad luck. But I would be happy for any idea. 

I will send you the blog name privately, Johannes.

**Comment by johanneszab** [comment]
Currently, some hidden tumblr might work for someone, for someone else not. Several people now wrote me that some hidden tumblr fail to be added with the error message: "cannot be parsed" and after hoovering over the error message the details say: unexpected character: "<".

I've found out that is has to do with the cookies. Maybe it's even related to your tumblr account settings. I don't know yet.

But I can say that sometimes it does download, sometimes not. Sometimes it helps to re-authenticate, sometimes not. The error also only started a few days ago (maybe as part of the new ToS/GDPR). I could also download a blog someone else showed with zero issues using my account while I couldn't download the blog using the account of my mail contact. I've also seen a video doing the same steps I've done where the download failed, while doing the same here, the download was possible.

**Comment by Kvothe1970** [comment]
I can confirm, the last release  **TumblThree] v1.0.8.51** fixes this. Tested with the test account I created as well. Thank you for getting this sorted out!  :)

**Comment by johanneszab** [comment]
Thanks for all your help, the blog and for sharing your account information! Much appreciated!

It's kinda weird for me though because I couldn't reproduce this error with my usual account. A newly created one had the same issues as yours. But based on the code I've changed and what I think the issue here was, it makes no sense that I didn't had this issue in the first place.

**Comment by Kvothe1970** [comment]
It was my pleasure. I agree it's odd. As if Tumblr treats accounts different based on something unknown. It can't be location based with both of us in Germany and frankly I will never get how tumblr decides to change code/API/the app/ the website it's shambles.
