### ISSUE TITLE
some tags don't work.

### ISSUE THREAD

**Issue by Imaginos9** [johanneszab/TumblThree#244]
Whenever I have a tag that has a dash in it - tumblethree won't download anything from the person's blog.  Example would be my-art or Joes-images-are-here. 

No idea if tags can have spaces and if those download ok or not.  All my non dash - tagged tumblr sites download just fine. Using version 1.08.48 and this has been going on for a few versions now from what I recall.

**Comment by Imaginos9** [comment]
If it is I have no idea what could be causing it. I just went to a new nsfw tumbler of an artist i'd seen years ago and when I put the tag my-art in his tumblr wouldn't download but when i removed the tag entirely it downloaded fine. That isn't the first tumblr that I've had this issue with. This is also a new install of windows 7, few months old at tops as my old computer died. 
Tumblr  tag my-art


| 
| 
|  | 
Tumblr

Tumblr is a place to express yourself, discover yourself, and bond over the stuff you love. It's where your inte...
 |

 |

 |




    On Wednesday, June 13, 2018, 10:25:57 AM PDT, Johannes Meyer zum Alten Borgloh <notifications@github.com> wrote:  
 
 
I've just created a test post in my test blog, tried to download a tag with a dash, no issue:

blog: https://privtumbl.tumblr.com/
post: https://privtumbl.tumblr.com/post/174555488822/wallpaperfx-lofoten-islands-sunset-wallpaper
tags: my-art, test, test test, myblog test



Maybe it's something else?

**Comment by Imaginos9** [comment]
This one also doesn't download anything with the tag in. It's also nsfw. 
tag the-potato's-art-crapTumblr


| 
| 
|  | 
Tumblr

Tumblr is a place to express yourself, discover yourself, and bond over the stuff you love. It's where your inte...
 |

 |

 |




    On Wednesday, June 13, 2018, 10:25:57 AM PDT, Johannes Meyer zum Alten Borgloh <notifications@github.com> wrote:  
 
 
I've just created a test post in my test blog, tried to download a tag with a dash, no issue:

blog: https://privtumbl.tumblr.com/
post: https://privtumbl.tumblr.com/post/174555488822/wallpaperfx-lofoten-islands-sunset-wallpaper
tags: my-art, test, test test, myblog test



Maybe it's something else?

**Comment by Imaginos9** [comment]
I get the same issue with your test blog :( I hope we can figure this out. Is there a file or something I can send you for more info? Here's my setup screen for the blog. Maybe i'm doing something wrong?
    On Wednesday, June 13, 2018, 10:25:57 AM PDT, Johannes Meyer zum Alten Borgloh <notifications@github.com> wrote:  
 
 
I've just created a test post in my test blog, tried to download a tag with a dash, no issue:

blog: https://privtumbl.tumblr.com/
post: https://privtumbl.tumblr.com/post/174555488822/wallpaperfx-lofoten-islands-sunset-wallpaper
tags: my-art, test, test test, myblog test



Maybe it's something else?

**Comment by johanneszab** [comment]
I can't see any of the images you've attached to your mail, but make sure that you use the latest version (v1.0.8.51) and not v1.0.8.48 anymore as you've stated in your initial post. Tumblr made some ToS changes that resulted in necessary code changes within TumblThree to properly work on Tumblr blogs.

Additionally, are you sure you've check marked the "download reblogged posts" or that the posts you are missing are not reblogs in case you've not selected that box?

**Comment by Imaginos9** [comment]
I'll update to 51 and see if there is a difference. I don't have reblogged posts checked because I only want the author's works which aren't reblogged :). Though I guess I do need to check that to test it out on your test site :/. I only attached a single image to the last post I sent you. No idea why you wouldn't get that. I'm sending these mails from Yahoo using Chrome browser, so they should be working ok.
On the artists blog it wasn't downloading any of his art at all unless I had no tag at all. Yet on other artists who have tags (none of which have a dash or space in the tag name) they download just fine. I'll update and see if that fixes the issue.
    On Wednesday, June 13, 2018, 10:45:39 PM PDT, Johannes Meyer zum Alten Borgloh <notifications@github.com> wrote:  
 
 
I can't see any of the images you've attached to your mail, but make sure that you use the latest version (v1.0.8.51) and not v1.0.8.48 anymore as you've stated in your initial post. Tumblr made some ToS changes that resulted in necessary code changes within TumblThree to properly work on Tumblr blogs.

Additionally, are you sure you've check marked the "download reblogged posts" or that the posts you are missing are not reblogs in case you've not selected that box?
