### ISSUE TITLE
Lost all my Tumblrs

### ISSUE THREAD

**Issue by ErikBrown2** [johanneszab/TumblThree#245]
When I started the program today it showed no Tumblrs while I had about hundred before. There was an error message that said that this could have been caused by a missing Tumblr. I restarted the program a few times hoping that it had a little bit of error handling. The error message did disappear but the Tumblrs stayed away. 

The index file is still there but the program appears to refuse to read it. What is now the best way to get the program to read the index file again? Typing in all the URLs manually wil be a lot of work. I am using version version 1.0.8.50.

**Comment by johanneszab** [comment]
How did you close TumblThree the last time?

Most likely the the settings are wrong/weren't saved and you've changed the download location but now it's just pointing to the default location. Open the settings, make sure it's set to the right location.

Also make sure, in case of you didn't restart Windows, that there is no stale TumblThree process in the Task Manager.

**Comment by johanneszab** [comment]
Otherwise you need to be more specific about the error message and maybe post screenshots of the settings and your location.

**Comment by johanneszab** [comment]
And please, upgrade to the latest version (v1.0.8.51) before doing anything! Most likely you've tried to download hidden tumblr that couldn't be processed because of the ToS changes. And maybe thats the reason why the application didn't exit properly and hence didn't upgrade your settings.

**Comment by ErikBrown2** [comment]
Everything worked fine and I think that closed it normally a few weeks ago. I use default setting for everything except for what to download. The blogs folder is under the folder where the application is located. I did not move it. I have upgraded to 1.0.8.51 but that did not make a difference.

I cannot find an error log file. Is there such a file to find the detailed error information?

**Comment by johanneszab** [comment]
> I cannot find an error log file. Is there such a file to find the detailed error information?

No such file.

So, in your download location (i.e. Blogs\ relative to the TumblThree.exe), there is folder Index, whats inside there?

There is no new error message after you start TumblThree?

**Comment by ErikBrown2** [comment]
For all my old Tumblrs (that are now missing) the file TumblrName.tumblr is missing in the index folder. When I add a new Tumblr then two files are created in the index folder. The file TumblrName.tumblr and the file TumblrName_files.tumblr. But for all Tumblrs that I had till today, only the file TumblrName_files.tumblr is there. So it apears that for some reason the application has deleted all the TumblrName.tumblr files. 

When I add a Tumblr that was existing before, then a new TumblrName.tumblr file is created but the old TumblrName_files.tumblr stays there. Just in case this is relevant, I have quite a long path to the index folder. This is G:\ErikTemp\TumblThree\TumblThree\Blogs\Index

**Comment by johanneszab** [comment]
If the *.tumblr files are missing, you'll have to re-add all your blogs. Sorry.

The files you've downloaded however will not be re-downloaded again because TumblThree checks if there is a file with that name already and if it has the same size as the potential download would have, it skips it.

**Comment by ErikBrown2** [comment]
Thanks for your replies. I will use this as an opportunity to clean up my list of Tumblrs. Thanks for the great program.

**Comment by ErikBrown2** [comment]
Thanks for the tip. I will do that.

**Comment by keokitsune** [comment]
the method i use is open index folder and use explorer to remove all files with the word file in its name, that will remove the blogs from the list but leave the database so you don't loose the global download list.

from that point ill use left shift and right click the folder were the blog folders are located and open the powershell window, then enter "Get-ChildItem | Select-Object -ExpandProperty Name > files.txt" which will create a text file of all your folder names, copy past that into note pad plus and use the find and replace option, use ^ and replace with https://, then find $ and replace with .tumblr.com  . open your program and enable copy from short cut and just copy the whole file to readd all your blogs.
