### ISSUE TITLE
[Help] Help testing the upcoming release!

### ISSUE THREAD

**Issue by johanneszab** [johanneszab/TumblThree#247]
Hi all.

I've changed the cookie handling a bit. I was wondering if anyone has some spare time and can test it a bit more, just to make sure that nothing is broken.

I've also implemented the tumblr login procedure in code so that we might eventually drop the Internet Explorer if necessary when it's obsolete. It should be possible to use both (the old IE way, or entering user/password in the settings).

**Changelog:**
**Beta2**: Fixed crash if user/password is wrong or if already authenticated and authentication was performed again.
**Beta3**: Got rid of the Internet explorer cookie handling as it's fundamentally broken ([you cannot load/save cookies without subdomains but with a dot prefix](https://github.com/dotnet/corefx/issues/11795)). The cookies are now stored together with the settings (%LOCALAPPDATA%\TumblThree). You'll need to reauthenticate once.
**Beta4**: Some UI improvments regarding the authentication. Pressing enter now advances to the next logical step.

Thanks in advance!

**Comment by hackedbyxx** [comment]
it still can't authenticate,i log in to it already for some times,but it still needs me to login

**Comment by johanneszab** [comment]
Thanks. It was the same issue I've run into already during the ToS/GDPR change. It worked with my test account, but not with a newer, second test account I've made. The issue is that you cannot save cookies with a dot (.) prefix using the wininet.dll api and then authentication might not survive into a new TumblThree session. That api is just awkward.

The cookies are now stored as .json in the settings folder.

**Comment by johanneszab** [comment]
Yes, email address of course. The same credentials you'd enter using the website.

**Comment by hackedbyxx** [comment]
@johanneszab so have you solve this problem yet

**Comment by Taranchuk** [comment]
Okay, then it's all right. But it may be worth changing tumblr login to the email address, just to avoid the misunderstandings of others. Just as a suggestion.

**Comment by hackedbyxx** [comment]
thanks,i have not see the beta4  in this issue before,now its ok to download my liked posts

**Comment by Kvothe1970** [comment]
Eh, how do I enter my second factor? I have 2factorauth turned on on my blog. I am using the email as the login and get the "click link" mail but it seems there is no way to enter my second factor, am I correct this is not supported?

**Comment by johanneszab** [comment]
Not implemented. I haven't looked at it, but I'm guessing it's just an additional POST request/step.

**Comment by Kvothe1970** [comment]
Thank you for the quick implementation, it works like a charm :)

**Comment by UnknownDave** [comment]
I do not have 2factor authorization; hence there is no 'verification' number/code to enter, which stops any downloading, or appears to be the main inhibitor ….

**Comment by johanneszab** [comment]
see #259 for the same question.
