### ISSUE TITLE
Cannot add blogs end with 'www'

### ISSUE THREAD

**Issue by poyshu** [johanneszab/TumblThree#248]
Hi. The app prevents "*www.tumblr.com" from being added. Any blog ends with www (i.e. meowww) can not be added to ThmblThree, the button greys out. Could you change that please?

**Comment by johanneszab** [comment]
Thanks for sharing! I will be possible to add blogs ending with _www_ in the next release.

**Comment by poyshu** [comment]
Whoa, thanks for the quick release and your amazing work!
