### ISSUE TITLE
The program skips some files at downloading

### ISSUE THREAD

**Issue by Taranchuk** [johanneszab/TumblThree#25]
When I adding blog to the download queue, the program are starting downloading, but at the end of downloading it show that the program don't downloaded several files from blog. In the details window, it looks like this: "Download images: 9427/9436, duplicates found: 0". The same happens with other blogs, the program are always not downloading several files from blogs. I tried remove from disk downloaded blog and re-downloading it to keep track of whether the same files skipped or not. It appears that files skipped randomly, not same files as at first downloading.
I have several times changed the settings, I set scan connection to 1, parallels connection to 1, parallels blog to 1, timeout to 1250, all of the above does not help. Also tried deleting setting.xml file in AppData, this doesn't help. 
It situation is sadly for me because a week ago I added many blogs to queue crawling and today I saw that all finished blogs are downloaded at 99.5-99.9 percent, there are no completely downloaded blogs, total were downloaded 500+ thousands files thus were skipped 2500+ files.
I dont know why this bug appear with me, maybe it is because of my internet connection or something wrong with my computer. Now at older versions such bug are repeated, but a two month ago when the last time i downloading images there was no bug in the older versions, all the blogs with all the files were downloaded correctly before.
I in desperate because so many files were skipped and no possible re-downloading them, only re-downloading all blogs.
Maybe it makes sense to introduce option to checking folders for missing files to further downloading this files?
P.S. English is not my native language, so sorry for possible mistakes in the text.

**Comment by Taranchuk** [comment]
Please answer the question. This is an important topic for me.

**Comment by blezinski** [comment]
yeah i noticed that one too
check my screenshot
http://puu.sh/ueq2s/72db4c1f5a.png

**Comment by Taranchuk** [comment]
OK, so I'm not the only one who has faced this trouble. Your screenshot shows almost the same situation as me.
Let's see what we have in common. I'm using Windows 7 64bit, .Net Framework 4.6, TumblrThree latest version, the speed of my Internet connection - 1 Mbps.

**Comment by blezinski** [comment]
> Let's see what we have in common. I'm using Windows 7 64bit, .Net Framework 4.6, TumblrThree latest version, the speed of my Internet connection - 1 Mbps. All the blogs that I add to the program is NSFW and contain a thousands of images.
yeah i've got all that in common too but my internet speed varies from 4MB/s to 400KB/s

**Comment by johanneszab** [comment]
It's more likely that the counting of downloadable files counts something multiple times or that something already downloaded wasn't properly registered in the downloaded files counter. That might happen if the program terminates in a state I didn't anticipate and it's all multi-threaded which has its own issues. It actually does a full rescan. The message _"evaluating xxx of xxx tumblr posts"_ in the queue window is exactly that.

Do you have a specific blog were files are actually missing?

I might take a look into this at some point (and I already did several times), but finding such things is usually quite time consuming.

**Comment by Taranchuk** [comment]
johanneszab, thanks for the answer. For me personally, no special blogs whose files were skipped, only all the blogs have missing files. Look at a screenshot from blezinski, the same similar situation I have. I can give a link to some blogs for example. Note they all is NSFW.
http://scatterbatty.tumblr.com
http://fancyandy17.tumblr.com
http://nudegirlserotica.tumblr.com
http://sinfullyspicy.tumblr.com
http://datys.tumblr.com
http://middelmaddel.tumblr.com

**Comment by johanneszab** [comment]
May be related to #72 where the grabber sees files but they are actually inaccessible and cannot be downloaded.

**Comment by Taranchuk** [comment]
Yes, it really can be this case. When I completely finish downloading the blog and after this download the list of links and when I comparing downloaded files with links in the text file it turned out that all links with file names that are not on the disk are inaccessible in the browser.

Now everything is fine with downloading files. At the beginning, the program really does skip some files, but after a second and third crawling with forced scanning and checking the directories, the program downloads all the missing files. So this topic, I think, you can close. Thank you for working on the program!

**Comment by nolabusboy** [comment]
I have successfully downloaded several tumblr blogs I follow, but some of them, including my own do not download. When I click crawl it just says evaluating for a while and then nothing downloads. ???
