### ISSUE TITLE
Expriencing Problems Using the App behind a VPN

### ISSUE THREAD

**Issue by TheC0d3Mast3r** [johanneszab/TumblThree#250]
So here's the deal, due to sweeping governmental censorship, I tend to use a VPN called Psiphon3. I use this app for browsing almost any social network including Tumblr.com. And when I want to use TumblThree behind it, the app won't work! 
The indicator shows that the blog is on, but it just stands still and nothing gonna happen afterwards. I have read how to setup an IE proxy setting but the problem is that I'm using kinda VPN that it only has connect or disconnect button, and nothing really more than that. I cannot find neither "Port" nor a "Usr/Pass" for it! and in proxy settings in IE or FireFox I put the related proxy settings on "Detect Automatically" and browsers bypass the filteration just fine. but dunno how to make ThumblThree to do the same trick.

One more clue around the problem, when I navigate to "About" and then click "checking for the latest version" this error pops up: " the remote name could not be resolved: 'psiphon3' "

**Comment by johanneszab** [comment]
Works fine for me. I've just tested it with two different providers, no issue. If you use a VPN, you don't have to setup anything other than your VPN software. Only if you use a proxy, then you'll have to fill in the Windows/Internet Explorer proxy settings.

![tumblrthree_behind_vpn2](https://user-images.githubusercontent.com/1684561/42407433-dc59941c-81bc-11e8-84d4-779c27b60131.png)
