### ISSUE TITLE
TumblThree hangs on /liked/by/ that results in Request denied

### ISSUE THREAD

**Issue by ErikBrown2** [johanneszab/TumblThree#251]
TumblThree hangs when it tries to download a /liked/by/ that results in Request denied. For instance, add the following link to the list of blogs and add it to the queue: https://www.tumblr.com/liked/by/peter

It causes TumblThree to hang when it tries to download it. Clicking on stop does not recover it and exiting the application and then closing the application in task manager appears to be the only way to get out of it.

**Comment by johanneszab** [comment]
Thanks for sharing! That will be fixed in the next release.
