### ISSUE TITLE
error 1 could not load file in library 

### ISSUE THREAD

**Issue by sidenora** [johanneszab/TumblThree#253]
I just couldn't load my blog library anymore. If it is a bad item in my index I do not know how to find it..Is there are way to point it out?

**Comment by johanneszab** [comment]
The questionable file is mentioned directly after the string you've pasted:

![couldnotloadfile](https://user-images.githubusercontent.com/1684561/42553361-e0240ce0-84e0-11e8-97e1-650b3b10dd95.png)

I've also described the default database location in the [README on the main site](https://github.com/johanneszab/TumblThree). And I'm sure there already is at least one [issue covering the same question](https://github.com/johanneszab/TumblThree/issues/6).

So, the file in my case is relatively to the TumblThree.exe -- as I've not changed the default download location -- then in Blogs\Index\wallpaperfx.tumblr.
