### ISSUE TITLE
Dashboards Only Blogs

### ISSUE THREAD

**Issue by NakedMirrors** [johanneszab/TumblThree#264]
Good Evening,

Is there a way we can download a blog that is only viewable on the dashboard sidebar thing and has it's archive locked?

**Comment by johanneszab** [comment]
Please read the readme before opening issues which are already answered there.

You can also use the dashboard urls to trigger the clipboard monitor: [www.tumblr.com/dashboard/blog/`blogname`](https://www.tumblr.com/dashboard/blog/sexyperfectbodies).
