### ISSUE TITLE
Cannot download raw pictures

### ISSUE THREAD

**Issue by harryhzg** [johanneszab/TumblThree#267]
cannnot download raw, the resolution is always 1280

**Comment by johanneszab** [comment]
It's literally one issue below yours. Read the already opened issues before opening a new one!

**Comment by johanneszab** [comment]
Duplicate of #261.

**Comment by johanneszab** [comment]
![tumblthree_raw_image_issue_dup](https://user-images.githubusercontent.com/1684561/45378292-54459600-b5fd-11e8-8cc3-68d626972491.jpg)
