### ISSUE TITLE
Issues with custom domains on Tumblr

### ISSUE THREAD

**Issue by shawnw-sh** [johanneszab/TumblThree#272]
Experienced an issue when I tried to download pics from a Tumblr blog which had a custom domain (for example, https://fiddle.se) 

It looks like that TumblrThree wouldn't recognise the URL with custom domains, even if they were actually linked to Tumblr.

Not sure if it is possible to add support for such blogs as well. 

Thank you.

**Comment by johanneszab** [comment]
See [this #21 issue](https://github.com/johanneszab/TumblThree/issues/21) on how to add them.

**Comment by shawnw-sh** [comment]
Thanks for the tip. All sorted. Sorry that I didn't notice that thread earlier.

**Comment by shawnw-sh** [comment]
Thanks for the tip. All sorted. Sorry that I didn't notice that thread earlier.
