### ISSUE TITLE
find which file is causeing "could not load file in library" 

### ISSUE THREAD

**Issue by keokitsune** [johanneszab/TumblThree#273]
is it possible to add a list when the error comes up to say what files it cant load?

**Comment by johanneszab** [comment]
So you mean there is usually more than one blog failing that you need a _list_ of blogs? It never happened to me, thus I've implemented it that stops at the first serialization exception.

**Comment by johanneszab** [comment]
Related to #253 #6.

**Comment by johanneszab** [comment]
Hmm, I see.
I've implemented showing all failing blogs for loading the .tumblr* databases, but for the _files.tumblr* there is actually nothing that handles anything. I must have forgotten that during the splitting of the databases.

I'll postpone adding this to the weekend. I'll upload a new release with all the latest commits then as well.
