### ISSUE TITLE
No images are downloaded.

### ISSUE THREAD

**Issue by Gromily4** [johanneszab/TumblThree#277]
when downloading images from the site, zero-size files appear. in this case, the downloaded counter is at zero. and blog_files.tumblr downloaded files are missing.  v1.0.8.61 and below.

**Comment by Gromily4** [comment]
OLD https://data.tumblr.com/
NEW https://66.media.tumblr.com/

**Comment by johanneszab** [comment]
Of course it doesn't work at all if you remove the _files.tumblr file. It's part of the blogs data structure. 

This never happened to me (that only the .tumblr file is there, but not the _files.tumblr), thus I doubt it programmatically just disappears unless you do run into some edge cases (crash during blog addition, no space left, ..).

**Comment by johanneszab** [comment]
Not sure what your second comment is supposed to mean though, thus I'll close this.
