### ISSUE TITLE
image is not downloaded

### ISSUE THREAD

**Issue by Gromily4** [johanneszab/TumblThree#278]
File storage server changed tumblr.com
OLD https://data.tumblr.com/0019df069c447cbe20d884d51130c9b1/tumblr_pgufpv5Bd61vkoceio1_1280.jpg
NEW https://66.media.tumblr.com/0019df069c447cbe20d884d51130c9b1/tumblr_pgufpv5Bd61vkoceio1_1280.jpg

since the server is tightly bound, changing the server causes the files to not be downloaded, files with zero size are created, but since the links are invalid the files are not downloaded.

src\TumblThree\TumblThree.Applications\Properties\AppSettings.cs

OLD private static string[] tumblrHosts =
            new string[]
            {
                "data.tumblr.com"
            };

NEW
 private static string[] tumblrHosts =
            new string[]
            {
                "66.media.tumblr.com"
            };
or not to put a rigid binding to the server, and to find out it in the process.

**Comment by johanneszab** [comment]
It's not true. The file storage didn't change at all. 

That defined data host is solely for _raw image files. TumblThree downloads from non-raw images from all **media.tumblr.com hosts. I've just tested the application, it works. And there is nothing "tightly bound" in the application at all. _raw files were an entirely different beast and required something like this. 

Sorry, but please, stop opening issues if you don't have validated that issue before or didn't understand the code. This considerably eats my time and reduces the already low development pace in this project.
