### ISSUE TITLE
Proofs of images not loading.

### ISSUE THREAD

**Issue by Gromily4** [johanneszab/TumblThree#279]
![proof 1](https://user-images.githubusercontent.com/43790893/47252648-a205b780-d461-11e8-8608-79d2a47a9a91.png)
![proof 2](https://user-images.githubusercontent.com/43790893/47252649-a29e4e00-d461-11e8-8475-622502243e8f.png)
![proof 3](https://user-images.githubusercontent.com/43790893/47252650-a3cf7b00-d461-11e8-8cba-1579e1d292d6.png)
![proof 4](https://user-images.githubusercontent.com/43790893/47252687-3839dd80-d462-11e8-8c2f-1a19aa76c979.png)
[images_url.txt](https://github.com/johanneszab/TumblThree/files/2497902/images_url.txt)

program the downloads, but together with this emerge files zero size. just files with zero size and what it depends on can't tell.

**Comment by johanneszab** [comment]
Works for me, same settings, also with default settings and leaving image size to _raw.

Is there an error about connection timeout?

**Comment by johanneszab** [comment]
![tumblr_nvktv0m5jk1ui2qj8o1_1280](https://user-images.githubusercontent.com/1684561/47254152-45ed6400-d45e-11e8-97bf-3bc6751263e8.jpg)

**Comment by johanneszab** [comment]
related to #278, #277.

**Comment by johanneszab** [comment]
Most likely not. As I've told you already, I've just downloaded all the files twice without any issue.

There was also no "program logic"-change a couple of months ago, thus it's probably not related to TumblThree. But feel free to commit any changes.

**Comment by Gromily4** [comment]
but I can't get to raw on https://data.tumblr.com/ because there is not anything available to or through one proxy. does not work and through a web proxy.
