### ISSUE TITLE
Could not save the blog

### ISSUE THREAD

**Issue by amigre38** [johanneszab/TumblThree#28]
When i try to add the blog:
http://p-e-n-e-l-o-p-e-m-a-c-h-i-n-e.tumblr.com

I get the error "Could not save the blog". If i look in the index folder the file was well created.
I then close and restart and it's ok the blog is in the list. Maybe a kind of name problem?
It's with the latest 19 version.

In fact after test, the new added blog were not downloading. I test on blogs already in the list, the refresh and download seems to work (seems only i don't know exactly what is done or not but at least i see some files downloaded). With the new blog added since the new version, it's like frozen during the first "evaluation" step.

**Comment by johanneszab** [comment]
Yes, the second file (_files.tumblr) containing the url/post list of downloaded files is not properly created. I tried to implement it independently of the download location and based on the the main settings (.tumblr) file. Seems to be broken.

I'll fix this later today. Thanks for letting me know!

**Comment by amigre38** [comment]
It's not completely ended, now in the 20 version when a blog file is correctly processed i get in the status the message:
"could not save the blog:.\Blog\Index\blogname_files.tumblr"
but when i put my mouse on top of this status, the name of the message is:
"Internal error description
cannot find a part of the access path "Rootfolder\Blog\Index\blogname_files.tumblr.tumblr"."

Maybe it's related
