### ISSUE TITLE
Error 3: post not parsable Element "root" from Namespace "" expected 

### ISSUE THREAD

**Issue by Kvothe1970** [johanneszab/TumblThree#280]
Hi, this has been happening for the past three days. With multiple blogs, it just pops up. I believe you changed the behaviour there back then with the hidden blogs and the unparsable contact back then, Johannes but this may be unrelated. For me the downloads stop with those posts. 

The internal error message is unfortunately in German so I will add a screenshot. 

Can anyone else confirm this behaviour? 
![image](https://user-images.githubusercontent.com/24984994/47769514-76de5c00-dcdc-11e8-8020-bbf8defd8c59.png)

This happens on both hidden and non-hidden blogs for me.

**Comment by johanneszab** [comment]
Thanks for sharing this issue.

I've started to look into it. It seems like they randomly return a blank site/answer instead of content. They do not even return a http error code, but instead a 200 (OK) with a blank site. Weird.

You can even try this in the browser by refreshing [this api page](https://wallpaperfx.tumblr.com/api/read/json?debug=1&num=50&start=500) several times, and it will randomly be empty.

**Comment by johanneszab** [comment]
Did you encounter the same for hidden tumblr blogs?

**Comment by Kvothe1970** [comment]
I’m reasonably certain I did. It’s not reproducible due to the random nature you noticed via the api. I’ll run the crawl again now and tomorrow morning using only the Hidden blogs.

**Comment by Kvothe1970** [comment]
Just ran the first round. First the hidden blogs, no troubles. After that I ran the normal blogs and it happened twice in a sample size of about 90 blogs compared to 30 hidden blogs.

**Comment by johanneszab** [comment]
Thanks for running the test.

I'll fix it tomorrow. Should be a simple one: I'd just have to wrap a method [around here](https://github.com/johanneszab/TumblThree/blob/master/src/TumblThree/TumblThree.Applications/Crawler/TumblrBlogCrawler.cs#L219) and re-call the api if the page is empty.

**Comment by Kvothe1970** [comment]
That’s brilliant, thank you :)

**Comment by Kvothe1970** [comment]
Just updated, crawled all blogs. No more errors, thanks for the quick fix :)
