### ISSUE TITLE
not added to the blog

### ISSUE THREAD

**Issue by Gromily4** [johanneszab/TumblThree#281]
I am trying to add a blog, but it is not added. blog https://fensu.tumblr.com/
the folder is created and that's it.

**Comment by johanneszab** [comment]
No issues here:

![tumblthree_fensu](https://user-images.githubusercontent.com/1684561/47979018-1b87e180-e0c1-11e8-9844-6f9966bf76f8.jpg)

**Comment by Gromily4** [comment]
in General, it is unclear how, but added. but I had a very long stick to add a blog. not that put in the address and blog added.
