### ISSUE TITLE
TumblThree not downloading any blogs

### ISSUE THREAD

**Issue by TheGoodCook** [johanneszab/TumblThree#288]
I am using the most current TumblThree however when I try to download a blog it just queues up then evaluates blogs by 50's and doesn't download anything. 

My Settings
https://i.imgur.com/fdpFiO6.png
https://i.imgur.com/Xnvw4kJ.png
https://i.imgur.com/ZXKVQTj.png

**Comment by johanneszab** [comment]
Important are the settings you see in the screenshot in the README under Details for each blog. It's also all explained in more detail there. Since I don't have the blog url, I cannot do anything more.

Note however that you have selected to NOT download any re-blogged photos.

**Comment by TheGoodCook** [comment]
It's multiple and even with the pages that i've selected the reblog option for. It basically runs counts through by 50's and doesn't even redownload. I've even made fresh new install without any old blogs and it still won't download. 

Another image
https://i.imgur.com/OF38JAR.png

devilhs-adult-art.tumblr.com
