### ISSUE TITLE
Not using proxy

### ISSUE THREAD

**Issue by WeirdoShaw** [johanneszab/TumblThree#291]
App version: 1.8.0.63
OS Build: Windows 10 Pro 1809

A working HTTP proxy is set in Internet Options, and access to tumblr.com is verified no problem using web browsers. 

All blogs reported offline by TumblThree, while looking at the verbose log of my proxy application, there's no traffic to tumblr through the proxy.

**Comment by WeirdoShaw** [comment]
I found the cause of this issue. In `Setteings.json`, the proxy related keys are set to outdated value. Remove the value of these keys solved the problem. 

The keys may be deprecated in the new version but it is stilled used  and the app does not provide a setting to change that. Please cosider remove or disable this in `Settings.config`

**Comment by johanneszab** [comment]
It already is. Read the change log. New users will not have this problem.
