### ISSUE TITLE
Limited Options for Downloading Liked Posts?

### ISSUE THREAD

**Issue by itsanapple** [johanneszab/TumblThree#292]
While going through the download with my liked content, it seems that there are less options to download compared to downloading from the normal blog.  
One of the issues being I can't download text from my liked stuff but I can on the other? 
Is there a way to download the text from the liked content section?

Thank you for your hard work!

**Comment by johanneszab** [comment]
Currently not implemented. Also see #175.

However, everything that is missing for that part is to grab the proper text parts and putting them into the queue. Similar as how it's done in the TumblrBlogCrawler. That could be done by parsing the HTML using a third party lib or by maybe even by reg ex.

If someone is interested in implementing this before the 17th of December, feel free to go ahead. I'll not have spare time for it.

You can see find the porper portions of the code here: [TumblrLikedByCrawler](https://github.com/johanneszab/TumblThree/blob/master/src/TumblThree/TumblThree.Applications/Crawler/TumblrLikedByCrawler.cs#L193), [TumblrBlogCrawler](https://github.com/johanneszab/TumblThree/blob/master/src/TumblThree/TumblThree.Applications/Crawler/TumblrBlogCrawler.cs#L406).

**Comment by johanneszab** [comment]
I'll close this as there already is an open issue for this topic.
