### ISSUE TITLE
Check if exception handling in ConfirmTumblrPrivacyConsent is correct

### ISSUE THREAD

**Issue by magicdmer** [johanneszab/TumblThree#295]
system:   win7 x64 chinese version
app:  1.0.8.63

I open tumblthree and wait a few minutes， it will crash without doing anything 
![](https://images2.imgbox.com/e8/d4/ydcJYq4i_o.png)

**Comment by johanneszab** [comment]
Maybe @Emphasia can help you here.

Did you try to specifiy a proxy in the Windows/Internet Explorer settings before TumblThree? Maybe the "agree to the new ToS"-Service is not properly implemented to handle exceptions, ..

**Comment by magicdmer** [comment]
> Maybe @Emphasia can help you here.
> 
> Did you try to specifiy a proxy in the Windows/Internet Explorer settings before TumblThree? Maybe the "agree to the new ToS"-Service is not properly implemented to handle exceptions, ..

After i set global proxy and it works ok now

**Comment by magicdmer** [comment]
Other question, i input username and password to login, it display TFA detected,enter auth code. But i'm not   
enable any safe setting in tumblr

**Comment by johanneszab** [comment]
Thanks. The crash will be fixed in the next release.
