### ISSUE TITLE
Not downloading external links.

### ISSUE THREAD

**Issue by MrSeyker** [johanneszab/TumblThree#297]
I'm not sure what has happened, when I made the back up of my blog, webmshare, gfycat and other external links to video were downloaded, but I'm currently trying to make back-up of SFM artists' blogs in lieu of the upcoming purge, and the aplication is just not detecting the external links.

All the tumblr media has been downloaded, same with imgur pictures, but none of the other links have downloaded.

This is the blog where I noticed the problem for certain, but I suspected something was off since I started the back-up process, as some other folders were oddly small given the amount of content I knew they released.

http://batesz2.tumblr.com

**Comment by johanneszab** [comment]
Simply because the other external sites are not implemented. 

You can try to _dump the crawler data_ or download the _text post_, see #296. Then you'll have to write your own parser to get the right links out of it.

Or you submit code to TumblThree to add additional external parser, see #269.

**Comment by MrSeyker** [comment]
If they are not implemented, then I don't understand why the back-up of my own blog is filled with gfycat files and webms from various sources.

**Comment by Hrxn** [comment]
Could be the post types on Tumblr. For example, a video post (just one single video), and a text post, with nothing inside but an embedded video, are two different things.

**Comment by johanneszab** [comment]
I'll release the next version maybe today, latest on Friday. That will contain general regular expression search, that crawls for all "*mp4/*mkv" (i.e. video files) and all image files in everything the crawler sees. Maybe we'll able get some more external videos/photos.

I only need to add missing check boxes to make this optional to the user interface as it will for sure add plenty of things more than once into the queue.

**Comment by johanneszab** [comment]
I'll close this, because there already is an open issue about the exact same topic as mentioned above.
