### ISSUE TITLE
Buttons greyed out

### ISSUE THREAD

**Issue by eproces** [johanneszab/TumblThree#298]
I feel like I must be missing something obvious. I just downloaded it, left all the settings alone, and tried to add a blog. 
Add Blog, Remove Blog, Show Files, Add to Queue, Remove from Queue are all greyed out no matter what I do. I put a URL in the box and nothing happens.

**Comment by rashidm** [comment]
The same for me. I can add blog name, but pressing [Add Blog] [Add to Queue]  and other buttons seem to have no effect at all. I can press [Crawl], the button gets blue frame around it, but no output.
Microsoft Windows [Version 10.0.17134.407]

**Comment by eproces** [comment]
Alright, that should have been more clear. Why wouldn't it be the actual URL? Or both should work. But it's fine for now.

**Comment by johanneszab** [comment]
> Why wouldn't it be the actual URL?

The whole url works perfectly fine for me? Any example of an url that doesn't work?
