### ISSUE TITLE
Application Download

### ISSUE THREAD

**Issue by GaThumper** [johanneszab/TumblThree#299]
Unable to download application via the link..

**Comment by johanneszab** [comment]
The application is this zip:
https://github.com/johanneszab/TumblThree/releases/download/v1.0.8.63/TumblThree-v1.0.8.63-Application.zip

from this page:
https://github.com/johanneszab/TumblThree/releases

Not sure what exactly is so hard in getting this right, and why this requires to open an issue in a development board?

**Comment by GaThumper** [comment]
I was able to download it on another system, it would seem that that first machine I was using was blocking it from being downloaded, was giving a blank white screen....  Thank you, great application...
