### ISSUE TITLE
New suggestion.... Justa suggestion. No comment duh......

### ISSUE THREAD

**Issue by alongeasy** [johanneszab/TumblThree#3]
Detail - what for? Never once see DETAIL FUCTION. WASTE OF SPACE.
Progress - what for two? Never see the function. Also waste of space.
Rating - use for? If tumblr not use any rating so tumblthree use for what?
Bottom button - i use 22 inch monitor screen but why must i scroll right and left if i want to SETTING or OPEN FOLDER.

In next version, can u make a setting to ENABLE/DISABLE EVALUATE? Maybe something good will happen. 

Also can u make a setting where tumblthree always automatically QUEUE its all blog and running indefinately? Just say because already QUEUE same 50 BLOGS AGAIN AND AGAIN until it TOTAL 5000 BLOGS IN QUEUE. This way, each blog getkick inits butt again so somehow will download something.

Tumbthree download video is the main reason i love it. So please consider this. 

Or just make a BETA version.

**Comment by speciose** [comment]
> Also can u make a setting where tumblthree always automatically QUEUE its all blog and running indefinately?

Have you tried shift to select multiple blog at once and clock "add to queue"? I can't test it because I don't have so much blogs but I though this would work in the future

**Comment by alongeasy** [comment]
Already have 50++ blog inside. Queue all 50 but many of them didnt last long. So add them more to queue up to 5000. So each blog available more than 100 times in queue. Some of them came back alive. Weird.



Sent from myMail for iOS


Saturday, 20 August 2016, 17:32 +0800 from notifications@github.com  <notifications@github.com>:
