### ISSUE TITLE
Error 1 not parsable posts per page. CANT DOWNLOAD FROM ANY BLOG

### ISSUE THREAD

**Issue by TMTTMTTMT** [johanneszab/TumblThree#302]
This is what I do:

Add blog 
Add to queue
Go to queue
Click crawl
And then I get error 1: A post from blog name was not parsable. Setting 'posts per page' to 1 in the Details might increase the downloadable content.
So I changed the posts per page to 0, to 1, to 10, but nope, won't work. How do I fix this?

**Comment by johanneszab** [comment]
I don't know.

Thats still happening for you? Do you use a proxy/vpn any kind of non direct connection to tumblr? Does that happen for regular tumblr blogs as well as hidden blogs or likes download?

**Comment by obendev** [comment]
Deleting settings in AppData helped in my case.
I messed up the settings with connections and so on.
