### ISSUE TITLE
Not downloading tumblr posts

### ISSUE THREAD

**Issue by Junior2232** [johanneszab/TumblThree#308]
I'm following the instructions to download a tumblr's post but nothing is happening. I add the tumblr to TumblThree and click Crawl, and it recognises there are posts to be downloaded under Number of Downloads, but under Blog settings Number of Posts they all say 0 of 0. I have all the default setting as well, so I don't know what the problem is. Thanks
<img width="960" alt="capture" src="https://user-images.githubusercontent.com/45614166/49488298-1e314e80-f89a-11e8-8753-4b10299224e1.PNG">

**Comment by johanneszab** [comment]
* Did you actually add the blog to the queue? Double click on the blog in the blog manager (left side panel), or drag and drop it to the queue, or press the "Add to Queue" button. The blog should then be visible in the queue pane, which is shared with the Details pane (right hand side).
* Make sure you've entered a correct date format if you've entered the "Download from" or "Download to" field. They are in YYYYMMDD.
