### ISSUE TITLE
crashes seconds after i open it.

### ISSUE THREAD

**Issue by Adun87** [johanneszab/TumblThree#311]
so as soon as i start it, it crashes. nowhere near long enough for me to even add a blog, let alone crawl one.

not sure what information i can give to get help with this.
EDIT: this started happening about 30 minutes ago, btw, had downloaded several blogs beforehand.

**Comment by saxoer** [comment]
same issue here

**Comment by Adun87** [comment]
its working for me now. it must be something on tumblr's end. closing this.

**Comment by johanneszab** [comment]
Sorry, I didn't see this earlier in this pile of issues/request in the last days.

It's probably related to #295 and should be fixed in the next release.
