### ISSUE TITLE
running painfully slow

### ISSUE THREAD

**Issue by scrappythepup** [johanneszab/TumblThree#312]
I am trying to download my blogs and currently it is running so slow that it has been working on a blog containing roughly 4000 items for over an hour and has only downloaded 1535 items so far on a system running 100MPS download speed. 
Any ideas??

Thanks

![img_6009](https://user-images.githubusercontent.com/45647194/49559434-d1229c00-f8dc-11e8-80db-aaaafee994de.jpg)
![img_6010](https://user-images.githubusercontent.com/45647194/49559438-d384f600-f8dc-11e8-8374-1cc05b0cd276.jpg)
![img_6011](https://user-images.githubusercontent.com/45647194/49559441-d4b62300-f8dc-11e8-8a3a-8e728a63d60f.jpg)
![img_6012](https://user-images.githubusercontent.com/45647194/49559445-d5e75000-f8dc-11e8-966b-31142d477be3.jpg)

**Comment by Anonymous-Mischief** [comment]
Only thing I can see is that the "Limit Bandwidth" is set to 2000 KB/s. I have mine on zero for unlimited. Still I wouldn't think 2 MB/s would be that slow. It's no fiber speed that's for sure!

**Comment by scrappythepup** [comment]
Thanks for the very fast response. I’ll try setting it to unlimited and see

**Comment by Hrxn** [comment]
And you have to take into account, with all of the backup action going on now, that the limiting factor may be on Tumblr's side.

**Comment by scrappythepup** [comment]
That was my first thought but I had a friend who also uses this program run the same blog on his machine and it went like lighting on his machine even though his internet service is 1/10th the speed of mine. 
It does look like increasing the bandwidth helped a whole lot.  

Thanks for all the support. Your awesome

**Comment by ki2007** [comment]
Noticed very high disk utilization too. But is is only reading not writing which seems to be the Problem here. My guess is that it has to do with the check to see if the file is already downloaded. As it slows down more and more after the initial 2-3k entries.

Is this check done against the Index files? Are they loaded from disk every time they are searched for an entry?
