### ISSUE TITLE
I have successfully downloaded several tumblr blogs I follow, but some of them, including my own do not download. When I click crawl it just says evaluating for a while and then nothing downloads. ???

### ISSUE THREAD

**Issue by nolabusboy** [johanneszab/TumblThree#313]
_Originally posted by @nolabusboy in https://github.com/johanneszab/TumblThree/issues/25#issuecomment-444694191_

**Comment by johanneszab** [comment]
Post a screenshot of your _Details_ pane of one of those blogs. Most likely you've messed up the blog settings (i.e., invalid date, nothing to download selected, no reblogs, etc. )..
