### ISSUE TITLE
how to force redownload my blog

### ISSUE THREAD

**Issue by ndxf** [johanneszab/TumblThree#318]
Hello,

I am backing up one of my blogs in light of the December 17 changes coming to Tumblr. For this, I set up the application to download overnight but forgot to plug in charger and the laptop died mid download. I didn't realize that I could just restart the scan, and instead deleted the folder of my blog from TumblThree/Blogs/ folder. Now when I start the Scan thing, it skips over thousands of images which I guess I deleted earlier? and I can't find any option to force a reindex or redownload of some kind. Can you please help me with this problem or let me know if I'm doing something wrong? 

Best,
NDXF

**Comment by johanneszab** [comment]
For re-downloading, you'll have to delete your blog from TumblThree. You can either do this 
* in TumblThree (sift-del key or via menus) or 
* delete the corresponding files in the TumblThree/Blogs/Index/ folder called after your blogs name. There should be two files, one is called blogname.* the other one blogname_files.*.

TumblThree will continue and skip already downloaded images and videos in the Blogs/blogname/ folder. Thus, it would not re-download already downloaded files, but re-download non-existing files, or resume incomplete ones.

But apparently, you just delete the wrong kind of files.

**Comment by ndxf** [comment]
Thank you so much for replying so quickly! It wasn't weird at all and fixed my problem! Thanks to your hard work I can save my Blog now :D Thank you again.

Best,
NDXF
