### ISSUE TITLE
Content of posts without titles is not downloaded

### ISSUE THREAD

**Issue by harryyhw** [johanneszab/TumblThree#327]
Any posts that don't have titles do not show up in the text file generated. This is true even after checking every box that determines which posts to download.

As an example, if I try to download the blog https://justanexamplefortumblthree.tumblr.com/, the resulting text file only has two entries, corresponding to the two posts with titles that were reblogged by the account. The other three reblogged posts, which don't have titles, are not in the text file at all. The same holds if I download as json.

**Comment by johanneszab** [comment]
There are only two "text"/regular posts. The other three are photo posts.

[images.txt](https://github.com/johanneszab/TumblThree/files/2660362/images.txt)
[texts.txt](https://github.com/johanneszab/TumblThree/files/2660363/texts.txt)
