### ISSUE TITLE
Only first photo of a post is downloaded

### ISSUE THREAD

**Issue by lil-spooky-vert** [johanneszab/TumblThree#328]
Posts that contain photo sets only download the first image in the set. I can see in the metadata that the photo set urls are being grabbed. Perhaps we could have an option to download those as well?

**Comment by johanneszab** [comment]
Thanks,

that was as well a bug introduced from the refactoring I did some weeks ago. Should be back working, and was only not working in the v1.0.8.6{4,5} releases.
