### ISSUE TITLE
Can't add NSFW blogs.

### ISSUE THREAD

**Issue by cijonson** [johanneszab/TumblThree#329]
Is it impossible to add nsfw blogs? When I try, nothing happens after pressing Add Blog button. I've tried many different nsfw blogs. Other blogs added without problems, only problem with nsfw.

**Comment by Hrxn** [comment]
No, that is not the problem. All kinds of blogs work.

**Comment by johanneszab** [comment]
Thanks @Hrxn for answering questions here!

For fine for me as well. No issues with NSFW blogs. Since you didn't specify what blog exactly, I'll close this.
