### ISSUE TITLE
Add Multiple Blogs At Once?

### ISSUE THREAD

**Issue by humanitiesclinic** [johanneszab/TumblThree#331]
Is there a way to add multiple blog urls at once? eg. from .txt or .csv file? Also, to mass-set all the setting for each blog at once?

**Comment by Kvothe1970** [comment]
This was asked multiple times, so Johannes made an extra FAQ 
[https://github.com/johanneszab/TumblThree/issues/301](url)

Please also have a look at: [https://github.com/johanneszab/TumblThree](url)
