### ISSUE TITLE
Will my downloaded site look and feel the same as the original? (have the same skin etc.)

### ISSUE THREAD

**Issue by humanitiesclinic** [johanneszab/TumblThree#336]
Will my downloaded site look and feel the same as the original? (have the same skin etc.)

I ask this question because I had a go with https://github.com/bbolli/tumblr-utils, but although it downloads content, the downloads don't mirror the original skin,look and feel of the site. It's because of this that I decided to try to find alternatives, and chanced upon your project.

"Themes in this cases means themes for TumblThree, not downloading a Tumblr blog theme."
Not very sure what this means. So, if I use TumblThree (instead of https://github.com/bbolli/tumblr-utils) can I get the original skin/feel of the site I wish to download?

**Comment by johanneszab** [comment]
no, it will not (#333).
