### ISSUE TITLE
Download full mixed posts

### ISSUE THREAD

**Issue by Void2258** [johanneszab/TumblThree#338]
I need to download all my likes. They are mostly combo posts with text and images together. However, so far I have only been able to get TumblThree to download the images; the accompanying text is left behind. Instructions seem to say this is possible, but if so how do I get the full posts downloaded, with the text and images combined as they are in the original posts?

**Comment by Capriciousuke** [comment]
> 
> 
> I need to download all my likes. They are mostly combo posts with text and images together. However, so far I have only been able to get TumblThree to download the images; the accompanying text is left behind. Instructions seem to say this is possible, but if so how do I get the full posts downloaded, with the text and images combined as they are in the original posts?

I think the program only allows videos and images/gifs to be downloaded in likes which kinda sucks imo.

**Comment by Void2258** [comment]
So how can I get full posts? Retweet everything (Several thousand) and then download my blog?

**Comment by johanneszab** [comment]
> Instructions seem to say this is possible,

I'm not sure where those instructions here should be? It's crystal clear written in the [README.md](https://github.com/johanneszab/TumblThree#likedby-backupdownload) under _Liked/by backup/download_. Additionally, there is also no option regarding download of text for liked by posts in any form in the application itself. So?
Then there are even multiple open issues/feature requests for exactly this, if you would have just looked before opening another issue for exactly this! One even from me, explaining in detail what's still left to do (#175, #232) and was opened more than a year ago.

> I think the program only allows videos and images/gifs to be downloaded in likes which kinda sucks imo.

If this kinda sucks imho, where is your contribution? Why don't you improve it? Open source doesn't mean, I have to support this application in any form, it doesn't mean I have to implement things random people would like to see.

**Comment by Capriciousuke** [comment]
> 
> 
> > Instructions seem to say this is possible,
> 
> I'm not sure where those instructions here should be? It's crystal clear written in the [README.md](https://github.com/johanneszab/TumblThree#likedby-backupdownload) under _Liked/by backup/download_. Additionally, there is also no option regarding download of text for liked by posts in any form in the application itself. So?
> Then there are even multiple open issues/feature requests for exactly this, if you would have just looked before opening another issue for exactly this! One even from me, explaining in detail what's still left to do (#175, #232) and was opened more than a year ago.
> 
> > I think the program only allows videos and images/gifs to be downloaded in likes which kinda sucks imo.
> 
> If this kinda sucks imho, where is your contribution? Why don't you improve it? Open source doesn't mean, I have to support this application in any form, it doesn't mean I have to implement things random people would like to see.

I'm not allowed to have an opinion? All I was saying that I think it sucks that you can't download other things besides images and videos through likes. I wasn't criticizing your program at all nor telling you to implement such a feature, however if you want to improve your program you have to listen to people's criticism of your program.

**Comment by johanneszab** [comment]
Yea, That's what I do and that's why there are 60+ open issues, some for years.
