### ISSUE TITLE
Concurrent blogs get stuck

### ISSUE THREAD

**Issue by KajinStyle** [johanneszab/TumblThree#339]
I am trying to download 2 blogs at a time but it keeps getting stuck. It handles the first 2 blogs just fine but once it moves on to the next two it gets hung up on evaluating the posts and gets hung up doing that.

Instead of downloading then evaluating the next 50 it continues to evaluate 50 at a time until it exceeds the number of posts (1050 of 1020 posts as an example). I am logged in and my internet connection can certainly handle it.

**Comment by gpriaulx** [comment]
I had some funnies like this too, but found if I tried again it worked. 

I had to:

- remove the blogs from the queue.
- remove the blogs from the list.
- Close TumblThree
- Delete the folders created for them in the blogs directory (they were empty anyway)
- Relaunch TumblThree
- Re-add the items.

I don't know what got me into this state to debug it through. If you work it out add some details ^^.

**Comment by KajinStyle** [comment]
Ok I figured it out. After reading another issue/thread I saw it being mention to clear "%appdata%/local/ThumblThree" settings. I just deleted the entire folder TumblThree. That cleared up my problems and other little problems I kept running into with it getting stuck. :)
