### ISSUE TITLE
Do embedded movies get downloaded?

### ISSUE THREAD

**Issue by humanitiesclinic** [johanneszab/TumblThree#341]
@johanneszab Even with the right settings, i.e. "Download videos" checked, I have some posts where Instagram and youtube movies are embedded in the original, but I cannot seem to find them in the downloads. Is it possible with the current version of the program to do so? If yes, what setting should I adjust?

**Comment by johanneszab** [comment]
It's not possible. Only the external hosts under External are supported. Youtube and Instagram for sure aren't under them. There are multiple issues open already that want support for more website (e.g. #269), but someone actually has to take the time and implement those by writing parser for them or by delegating the right information to already available other libraries to get the right stuff from their corresponding websites.

I'll personally not have the time for this before the 17th December.

**Comment by johanneszab** [comment]
I'll close this, because there are already open issues for this, if that's okay.
