### ISSUE TITLE
How to uninstall TumblThree

### ISSUE THREAD

**Issue by celticmage11** [johanneszab/TumblThree#344]
Please forgive my ignorance here. I was attempting to save my Tumblr and apparently am in over my head. 

I'm trying to uninstall TumblThree from a Windows 7 machine, 64-bit machine.  I placed it in a folder of its own on my Desktop. However, it doesn't show up in Programs, and since there are DLL files and such, it seems dangerous to me to simply move the entire folder to the trash. 

If someone could please advise on how to safely remove, I would greatly appreciate it.

Thank you.

**Comment by johanneszab** [comment]
Exactly right. Thanks @Hrxn!
