### ISSUE TITLE
Not downloading the whole post

### ISSUE THREAD

**Issue by Willmyb** [johanneszab/TumblThree#346]
When a post has multiple images it only downloads the first one and then moves on to the next post. What can do I do so it downloads everything?

**Comment by Taranchuk** [comment]
The program should download all photosets. Are you using the latest version? If yes and the program does not download photosets, then you must provide a link to a post with photosets that the program cannot download so that the developer can fix it.

**Comment by Willmyb** [comment]
I see there was a new realease 22 hours ago, I will try with it. thx

**Comment by Willmyb** [comment]
still doesn't work, here's a post it only downloads the first pic:
http://infinite-movement.tumblr.com/post/181016283490/sekhou-drame-by-kapturing-for-essential-homme

**Comment by Taranchuk** [comment]
With the new release, try to delete the blog and add again and start the download. Perhaps just when you downloaded the blog on an old release, the posts url with photosets was recorded in the index file, so the program skips them on the next crawling.

**Comment by Willmyb** [comment]
I think that did the trick, now it's downloading everything, thank you very much.

**Comment by johanneszab** [comment]
Thanks a lot @Taranchuk!
