### ISSUE TITLE
Cannot add blog

### ISSUE THREAD

**Issue by godlydevils** [johanneszab/TumblThree#35]
http://iglovequotes.net/

Although it's tumblr blog, I cannot add it

**Comment by Taranchuk** [comment]
Try it
http://iglovequotes.tumblr.com
Also look at this comment from amigre38, it describes how to solve problems with not-tumblr web-address blogs.
https://github.com/johanneszab/TumblThree/issues/21

**Comment by johanneszab** [comment]
Duplicate of #21.
