### ISSUE TITLE
tumblthree.exe file missing from my download?

### ISSUE THREAD

**Issue by curiouslittlebird** [johanneszab/TumblThree#356]
very sorry for the stupid question, but where might I find the actual tumblthree.exe file?  I just downloaded what I suppose is the latest release about an hour ago.  I have searched the extracted .zip file (both manually and by search bar) several times, looked all over the main page, resource page, etc., but have come up empty.  Was I supposed to click on something else?

**Comment by Bambr-name** [comment]
check this out https://github.com/johanneszab/TumblThree/releases/download/v1.0.8.61/TumblThree-v1.0.8.61-Application.zip   just unzip it and thats it, everything there

**Comment by curiouslittlebird** [comment]
Thank you!  This one worked!  (Looks like I accidentally downloaded the TumblThree-master .zip the first time instead of the latest release .zip, for anyone else who may run across this question)

**Comment by johanneszab** [comment]
Thats not the right file, this is: https://github.com/johanneszab/TumblThree/releases/download/v1.0.8.68/TumblThree-v1.0.8.68-Application.zip

And you should generally use the latest release you find under this URL: 
https://github.com/johanneszab/TumblThree/releases/latest
