### ISSUE TITLE
TumblThree can't download posts with multiple images o_O  Is it fixable? Need help!

### ISSUE THREAD

**Issue by Bambr-name** [johanneszab/TumblThree#357]
There is very common type of posts with several images inside, for example https://cutest-animals-here.tumblr.com/post/181119782205/source   So, right now TumblThree downloads ONLY first image and rest of the images are not downloaded!   One out of two - either I am too stupid to understand the Settings or nobody cares about this BIG issue?   

I will be very grateful for any help! I need to download all the pictures from that kind of posts https://friendly-animals.tumblr.com/post/181033027154/source

------------------------
Lets try http://world-of-cats.tumblr.com - set "Settings" Download from 20181214 to 20181216
TT downloaded all images here: http://world-of-cats.tumblr.com/post/181111695607/my-silly-baby-boy-coco
and only the first image here: 
http://world-of-cats.tumblr.com/post/181124322525/took-gary-to-a-local-ice-climbing-area-he-loved
http://world-of-cats.tumblr.com/post/181105965661/fortunatelystuff-comic-printed-hoodies

and completely SKIPPED this posts:
http://world-of-cats.tumblr.com/post/181092603719/source
http://world-of-cats.tumblr.com/post/181096736880/source

**Comment by Bambr-name** [comment]
I will be very grateful for any help!  I need to download all the pictures from that kind of posts [https://friendly-animals.tumblr.com/post/181033027154/source](url).

**Comment by johanneszab** [comment]
Did you check the latest issues before opening yours at all (#328)?
Did you read the latest change/release log before opening this issue?

**Comment by Bambr-name** [comment]
Thank you a lot!!!!!!   It was 1.0.8.64!!!
