### ISSUE TITLE
Bugs in the version 1.0.4.25

### ISSUE THREAD

**Issue by Taranchuk** [johanneszab/TumblThree#37]
1) When I select the mode of downloading images and meta-data of images in the details view, they are all downloaded at crawling, but in the details view the downloader value of images and metadata goes only in the images value, leaving the metadata value empty.
2) When I set the force rescan mode for the blogs, the download count in the column abnormally increases so it becomes greater than number total of images in the blogs and number images in the metadata. And after repeated forced scanning the values of download only increased.
3) After the forced scan with mode downloading metadata the program creates duplicate entries in the metadata files, in fact whole copies of meta-data are downloaded and created inside the text of the files of metadata.
4) Forced re-scanning does not work for deleted or renamed files, they do not download again. But it looks like all the missing files are downloaded after forced rescanning.

P.S. Sorry for possible mistakes in the text, English is not my native language

**Comment by johanneszab** [comment]
Thanks for sharing.
