### ISSUE TITLE
TFA detected, don't have it.

### ISSUE THREAD

**Issue by nonyabeez** [johanneszab/TumblThree#372]
I downloaded the program to save my likes, I set everything up and hit crawl to download, said I needed to authenticate, I entered my credentials which im sure are correct, but I then get the prompt for TFA. I don't have TFA but I think two things may be causing this, either the me recently changing my password, or tumblr giving you the choice to choose between logging in via password or "link" sent in email being mistaken as a captcha, anyone else have this problem? I browsed two other threads about this problem and tried the solutions like updating browsers and such but it did not work. I believe (#259) and (#307) where what I looked at before posting this. thank you for your time!

this is the choice that tumblr gives you when you enter your email when logging in!
![tumv](https://user-images.githubusercontent.com/45924043/50059128-c74c3480-0137-11e9-957c-6041ead40d6c.PNG)

sorry if this has been solved before!

**Comment by gpriaulx** [comment]
I get the nag screen too when I log in about using a magic link or password, but no issue with TumblThree authenticating. Sorry I can't offer any further insight at this time.

**Comment by nonyabeez** [comment]
I appreciate the comment! It may be something else, but knowing it works with this screen narrows it down! thank you!

**Comment by nonyabeez** [comment]
HEADS UP, using a slightly older version worked!
https://github.com/johanneszab/TumblThree/releases/tag/v1.0.8.51
this was mentioned by stillwaterspony in (#307)
worked for me so if you're having a similar problem try it!
