### ISSUE TITLE
Not working at all as of 25 minutes ago

### ISSUE THREAD

**Issue by SwimmingLink** [johanneszab/TumblThree#374]
I'm assuming Tumblr changed something as they said this was the deadline for NSFW stuff... All I can get it to do now is evaluate tumblr post URLs, then stop... never finds downloads to get... Stopped right at Midnight Eastern Time.

**Comment by Hrxn** [comment]
Yeah, seems to be working for me as well, as of 11:30 am CET..

**Comment by SwimmingLink** [comment]
Not really sure what happened. I trashed my (portable) install of it and started over and it's able to find the downloads again... I guess I just jumped to (an incorrect) conclusion when it broke mid-download at the turn of the hour on announced date...

I don't see a way for me to close this issue myself, so if a mod can close this, that'd be great. Sorry and thanks :)

**Comment by Hrxn** [comment]
You can close issues as the opener.

**Comment by SwimmingLink** [comment]
Totally missed the button at the bottom.
