### ISSUE TITLE
[Bug] Manager right-click context actions unavailable

### ISSUE THREAD

**Issue by gpriaulx** [johanneszab/TumblThree#375]
In my debug build at the latest head, if I right click an item in the manager list I am presented with some contextual options. Half of these remain disabled despite right clicking on an item. Benign operations like "Copy URL" cannot be actioned. Selection is still acknowledged as many other actions are available. 

This appears to be working fine in my test VM with the latest release; at this point I am unsure what is different.

![copyurlissue](https://user-images.githubusercontent.com/8568379/50082414-fef4d280-0244-11e9-91aa-d7c8c372cdda.gif)

**Comment by gpriaulx** [comment]
Ok - a pattern! 

At startup, if I right click on an item immediately without selecting one first, the applications becomes stuck in a state where some context actions are disabled. If I click and select a row first and then right click, everything is happy and I can then immediately right click on other rows as expected.

![copyurlissue2](https://user-images.githubusercontent.com/8568379/50082828-09639c00-0246-11e9-8bb8-d7e6e2aa83e3.gif)

**Comment by tehgarra** [comment]
I always wondered about that. I've been dealing with this on and off throughout the year but never understood why

**Comment by gpriaulx** [comment]
I guess now you know you are not crazy. haha. It confused the hell out of me too. 
I'm keen to separate the service level components from the view models a bit more - I think that would make this sort of thing easier to avoid. I think the current PR I have put forward solves this specific issue for now though.

**Comment by johanneszab** [comment]
I've had this seldom happening as well, but I never cared/had the time to sort it out :).

Thanks again @gpriaulx for fixing it and creating the pull request!

**Comment by gpriaulx** [comment]
No problem ^^
