### ISSUE TITLE
How do I download actual files through URL list files?

### ISSUE THREAD

**Issue by gehdapinu** [johanneszab/TumblThree#377]
I downloaded URL list files before December 17th. (images_url.txt, videos_url.txt, etc.)
I tested it today and I clicked the "crawl" button with "Download URL List" checked. It proceeded to work. However, the actual files were not downloaded.
There was no change in any folder.
How can I download actual image files and video files using url files?
![default](https://user-images.githubusercontent.com/45962252/50140008-afff7980-02e6-11e9-8431-0823d2d02c6f.png)

**Comment by Taranchuk** [comment]
Tumbltree cannot download files through the URL list. You need to use other tools. wget, for example, can download files using the URL list.

**Comment by gehdapinu** [comment]
> 
> 
> TumblThree cannot download files through the URL list. You need to use other tools. wget, for example, can download files using the URL list.

Can you use wget to tell me a command that can download video files and image files to each blog folder like TumblThree?
I do not know about programming.

**Comment by Taranchuk** [comment]
@gehdapinu Basic example:
`wget -i d:\Blogs\BlogName\images_url.txt -P d:\Blogs\BlogName\`

For each URL list in different folders, you need to learn how to use loops and variables in the shell scripting.

**Comment by gehdapinu** [comment]
> 
> 
> @gehdapinu Basic example:
> `wget -i d:\Blogs\BlogName\images_url.txt -P d:\Blogs\BlogName\`
> 
> For each URL list in different folders, you need to learn how to use loops and variables in the shell scripting.

Thanks. Taranchuk

**Comment by EC-O-DE** [comment]
https://www.youtube.com/results?search_query=tumblrthree

**Comment by gehdapinu** [comment]
> 
> 
> https://www.youtube.com/results?search_query=tumblrthree

Thank you for your reply.
But now I am downloading files with Wget.
The method described in the video is a general description.
What I want is to use TumblThree to read text files with URLs and to download files.
Unfortunately, TumblThree can not do that yet.
