### ISSUE TITLE
What’s going on 

### ISSUE THREAD

**Issue by momoneymoproblem** [johanneszab/TumblThree#378]
Tumblthree says I Downloaded  50000 I look into the folder it’s probably only 18,000 why is that, also some videos aren’t being downloaded/captured just the pic of the video y is that

**Comment by EC-O-DE** [comment]
the app scans for duplicates and only downloads 1 file per version

**Comment by EC-O-DE** [comment]
https://www.youtube.com/results?search_query=tumblrthree

**Comment by johanneszab** [comment]
See #351 for possible 3xx error codes that reduce the amount of possible downloads.

Currently, text posts are downloaded into a single file, thus if you downloaded 800 conversation posts, you'll not have 800 files in the download folder, but more like ten'ish.

You might want to turn on the `dump crawler option` or `downloaded xxx meta`.
