### ISSUE TITLE
Gif images not beeing previewed

### ISSUE THREAD

**Issue by WyattLW** [johanneszab/TumblThree#38]
Gif images not beeing previewed
I downloaded build v-1.0.4.26 (had bug with 1.0.4.25 already when i started using tumblthree)
(https://github.com/johanneszab/TumblThree/releases)
Windows 10 x64
.Net Framework 4.0.3

Is that a common bug or that's how it's supposed to be?

**Comment by johanneszab** [comment]
Thanks for reporting!

Should be fixed in the upcoming .30 release.
