### ISSUE TITLE
Not Working!

### ISSUE THREAD

**Issue by parodg18** [johanneszab/TumblThree#381]
I download your program.  Logged into my tumblr account through your programs settings.  Copy and paste my the url of my own tumblr blog...then literally nothing.  Help!

**Comment by EC-O-DE** [comment]
https://www.youtube.com/results?search_query=tumblrthree

**Comment by parodg18** [comment]
Yes, I did and literally nothing seemed to happen.

**Comment by Stevia333** [comment]
![2018-1220-1710 part one of tumblthree fix](https://user-images.githubusercontent.com/46036007/50316243-73b15200-047b-11e9-97c7-8a50b79e88fe.png)
![2018-1220-1712 tumblthree ask](https://user-images.githubusercontent.com/46036007/50316250-7b70f680-047b-11e9-9d22-0e2627f2c7ba.png)
i think you click something after it's added to the queue. perhaps it's "crawl". i just did a click of the mouse & it got started again

**Comment by gpriaulx** [comment]
This might be too much effort to ask, but if you would like better advice would it be at all possible to do a screen capture of what you are doing? 

1. Remove everything from your queue if anything is there.
2. Remove everything from your main list if anything is there.
3. Close TumblThree.
4. Delete all files in the blogs folder.
5. Set up screen capture stuff.
6. Open TumblThree.
7. Capture your steps to add your blog.

If everything looks correct and their are no subtle telltale signs of something going wrong, I will try and hunt it down. 

This may help. https://www.screentogif.com/

**Comment by parodg18** [comment]
I should have clicked on your video first.  As it turns out, I had simply
copied and pasted the url that appeared on google chrome into the enter url
space.  Problem was the url chrome gave wasn't in the form your program
recognized.  Everything is working fine now!

Thank you,
Paul Rodgers
