### ISSUE TITLE
[Feature Request]  Download actual files through URL list files (txt)

### ISSUE THREAD

**Issue by gehdapinu** [johanneszab/TumblThree#383]
First, read the link below.
https://github.com/johanneszab/TumblThree/issues/377

TumblThree can create a URL list file (txt) to access the actual files (images,videos) of blogs, but it is impossible to read txt files and download the actual files.
Especially if want to download postings that have been made private since December 17th.
I am currently downloading through Wget,
It is more inconvenient than downloading via TumblThree.

**Comment by Taranchuk** [comment]
> Especially if want to download postings that have been made private since December 17th.

Just for your information, you can still download videos and images, even private ones (NSFW), feel free to download them as usual, there is no need to download URL lists.

**Comment by gehdapinu** [comment]
> 
> 
> > Especially if want to download postings that have been made private since December 17th.
> 
> Just for your information, you can still download videos and images, even private ones (NSFW), feel free to download them as usual, there is no need to download URL lists. Tumblr has not yet closed access to them via api, so TumblThree can download them.

Thank you for giving me good information every time.
I just tried. It works.
