### ISSUE TITLE
Settings are always saved.

### ISSUE THREAD

**Issue by tekko** [johanneszab/TumblThree#41]
It's not a big deal and I don't know if it's by design. I just found it weird that the settings are saved without pressing the save button. If I just close the settings window, the settings are saved anyways.

**Comment by johanneszab** [comment]
I've done that deliberately because it was easier for me to test the application in the beginning as I haven't had setup the buttons then.

We could change it, I don't mind much. It's probably more common sense in the way how you propose it.
