### ISSUE TITLE
Option to grab the url list only

### ISSUE THREAD

**Issue by tekko** [johanneszab/TumblThree#42]
While the new _files.tumblr is good, it would be better to have an options to get those links only.

Having only the urls saved, but not the actual files, one can merge those lists outside the program.
Once merged, duplicated links can be cleaned and batch downloaded with a browser's extension saving space and bandwidth.

Just an idea. I've tried something similar by checking to download only the meta files. But those urls are blog specific if I recall correctly.

Thanks.

**Comment by Taranchuk** [comment]
I like this idea. This can be introduced in the form an additional download mode for only the URL list as a separate text file. This will also allow for example to check the number of URLs with the number of downloaded files, if any files are missing, then can weed out the downloaded URLs and download the remaining missing files.
