### ISSUE TITLE
Option to not redownload existing files if there are no index files

### ISSUE THREAD

**Issue by Taranchuk** [johanneszab/TumblThree#44]
It would be nice if the program did not redownload the already downloaded files but just skipped them in the case of absence index files for them. This would be actual if, for example, the index files were lost or deleted. I just have lots of downloaded files from blogs, that were downloaded year ago, I would like to update them to download new posts, but the index files have been deleted because I deleted blogs from the program due bug crash occurs after adding new blogs if existing blogs were so many in the program so now I have no index files for older blogs. And if I add all the old blogs to the program, then it will redownload all the files in the folders and this process will take a long time because I have over 500 thousands files. I know that you are currently working on program development or other things, so I do not expect that this option will appear in the program anytime soon or at all, but if there is an opportunity to introduce this option I will be happy because it will save a lot of time and internet traffic.

**Comment by johanneszab** [comment]
It's actually three lines of code to check in the directory instead I guess.

I've decided against in the beginning because for me at least on my crappy hard drives it takes some time to only open an explorer view in a folder with several ten thousand files. I can add that though as an option somehow ...

**Comment by Taranchuk** [comment]
Okay, so is it possible to write this in the code and this option will appear in the program? If so, I will be very glad, for me it is really necessary. Thanks!

**Comment by johanneszab** [comment]
Its implemented. I'll probably upload a release quite soon, but it might have other problems I've not stepped over yet caused from my code refactoring.

On the other hand it should be more stable now, easier for other people to join and maybe someone has time a write some unit tests to that it can be automatically tested.

**Comment by johanneszab** [comment]
Should be working, but I can not guarantee for anything right now. I've shuffled around quite a bit of code.

It can not load the old binary databases, only the new text based ones. So you might have to run TumblThree v1.0.4.31 or v1.0.4.32 to convert the databases to text files and then run this one. If you used the recent version anyways everything is already set.

[Uploading TumblThree-v1.0.4.33.zip…]()

**Comment by johanneszab** [comment]
Maybe I leave this open if there are any people how are willing to do the testing.
It's basically at the state of the latest commit johanneszab@ef4e270 with only the version number changed.

If you notice anything wrong, please write it here.

**Comment by Taranchuk** [comment]
The version 1.0.4.33 program does not download images at all, after scanning the blog disappears from the queue and there is not one downloaded file in the folders.

**Comment by johanneszab** [comment]
Whoops, sorry. It's probably too late for me already to think about logic. This should be working now. I've tested it with files and a database.

[TumblThree-v1.0.4.33.zip](https://github.com/johanneszab/TumblThree/files/862945/TumblThree-v1.0.4.33.zip)

**Comment by Taranchuk** [comment]
Thank you! It seems that it works. But there is one thing: a year ago, when I downloaded blogs, there was no function to download files with specified size. And now I'm downloading only with the function of downloading specified size. In practice, this means that I have many files in the older blogs with digits in the filenames like "_400", "_250", "_540" and now the program creates new same files next to them with the new digits "_1280". This is a small inconvenience, could this be fixed?
