### ISSUE TITLE
Release 1.0.4.34 - shift + click

### ISSUE THREAD

**Issue by amigre38** [johanneszab/TumblThree#45]
When i do a click on one item and then while pressing shift i click on another to select more than a number maybe 10-15 blogs  the program crashes.

**Comment by amigre38** [comment]
Strangely it cannot be reproduced while launched through the IDE of Visual Studio...

**Comment by johanneszab** [comment]
I could however. It accessing a collection which has been modified. Which is okay, since we only care for the last collection anyways.

Thanks!
