### ISSUE TITLE
Add a blog in the queue that make another one selected

### ISSUE THREAD

**Issue by amigre38** [johanneszab/TumblThree#46]
If i add a blog in the queue that contain the name of another blog i have this error.
The one that is contained in the first is selected too (even if it's not added for real in the queue and not processed.
in my list i have two blogs:
https://classicsyl20.tumblr.com
https://syl20.tumblr.com

So if i click on the first one the second is selected too.

**Comment by johanneszab** [comment]
Make sense. I've used Contains instead of Equals method.

Should be easy to fix.

**Comment by amigre38** [comment]
I try to find where it was done but to be honest i can't.
But now i have an error while loading a very big index folder and i think it's easier for me to find this new one.

**Comment by amigre38** [comment]
I found the new one, in fact it's partially my fault...
In the index folder i have a .svg file of a blog i don't want anymore.
Previously it was not a problem but now in this part of the code:

```
                        string json = File.ReadAllText(filename);
                        TumblrBlog blog = new System.Web.Script.Serialization.JavaScriptSerializer().Deserialize<TumblrBlog>(json);
                        blog.ChildId = Path.Combine(directory, blog.Name + "_files.tumblr");

```
The file is tested as a blog one and it doesn't have the good format. So that raise an error and prevent loading the other files.

**Comment by johanneszab** [comment]
I recently changed all .Contains() to a proper .Equals() methods where it made sense. I just tested if with the wallpaper.tumblr.com and wallpaperfx.tumblr.com blogs and there were no issues in adding the wallpaper blog to the queue or in restoring the queue at application start.

**Comment by johanneszab** [comment]
So, I'll close this. If you still have problems, you can reopen it.
