### ISSUE TITLE
Passworded blog crash

### ISSUE THREAD

**Issue by amigre38** [johanneszab/TumblThree#47]
If the blog have a password (an old one i have now need a password) then the program crash:
https://thatnakedchick.tumblr.com

I can reproduce each time i put in the queue and ask to crawl it

**Comment by johanneszab** [comment]
Yea, It's because I'm checking the url of the blog now, not the api url. Which returns a ok state even if it's private or password protected.
Should be easy to fix, but I wasn't sure how to do it without putting in too much specialized code. I'll think about it.
