### ISSUE TITLE
[bug] The value of the progress bar is not correct

### ISSUE THREAD

**Issue by Solstisse** [johanneszab/TumblThree#5]
The progress bar never gets to 100%, because the value of `blog.DownloadedImages` is refreshed **after** the progress bar :
https://github.com/johanneszab/TumblThree/blob/f7610efb7838cb943de9350a5bae6d9fe4d7f551/src/TumblThree/TumblThree.Applications/Controllers/ManagerController.cs#L338

```
blog.Progress = (uint)((double)blog.DownloadedImages / (double)blog.TotalCount * 100);
// ...
blog.DownloadedImages = (uint) blog.Links.Count();
```

![tumblthree_bug](https://cloud.githubusercontent.com/assets/21181082/17867725/f500570c-68ab-11e6-995e-e2b613f93de2.jpg)

**Comment by johanneszab** [comment]
Thanks for sharing and figuring this out!
Crystal clear description, even with screenshots, yaay! \o/
