### ISSUE TITLE
Option to download only a certain amount of last posts of the blogs.

### ISSUE THREAD

**Issue by Taranchuk** [johanneszab/TumblThree#52]
How much I understand from recent commits, the program development still proceeds? If so, it's very good. I have one request for adding one desired function, which I really want to see in the program. I often download a lot of blogs and I watch them all, but there are blogs that offer too poor quality content and I delete them from the computer so in consequence of this too many gigabytes of traffic is wasted. And I thought that it would be nice if the program had an option to download say only the last 1000 posts or 500 posts and then I will already be able to estimate the approximate quality of content in blogs by this posts just entering in a folder with sketches, so if there are bad blogs, it will be possible to remove them painlessly and also if there are good blogs, it will enough uncheck this option so that after this the program could download the entire blog completely. If you have the desire and free time to introduce this function and it will not be too hard to write this in the code, I will be very happy if this function appears in the program, personally for me it will be a very useful addition to the program. Thanks!

**Comment by Taranchuk** [comment]
What about this suggestion? I would like to know whether this will be implemented or not. I'm just a little confused by the fact that for 1.5 months after the creation of this topic there was not an answer and the "enhancement" label was not attached while in other topics they were. Does this mean that this suggestion will not be accepted or may this topic was unnoticed in the midst of other topics?

**Comment by johanneszab** [comment]
You can add this if you want. Thats why there is the sorce code.

Personally, I'll probably not add much in the next 6 months or so since I'm largely working on different things now and seldom use TumblThree myself. I've actually tried to fix the code in the last few month so that someone else can contribute more easily. Most new features were mostly byproducts or easy to add.

**Comment by Taranchuk** [comment]
OK. Unfortunately, I do not know anything about programming, so I can not do it. Good luck to you in other projects!

**Comment by johanneszab** [comment]
It's more work related and doesn't mean I won't code here anything anymore, but I won't add something immediately just because someone wants it ;)

**Comment by Taranchuk** [comment]
Thanks very much for the update! For me it's a very helpful function. It's very easy to evaluate the quality of blogs and I can continue downloading if the quality of content is at first glance good and I can also delete bad blogs. I will share a couple of observations. If set the page size to 50 and set downloads pages to 1-20 and compare the downloaded files to the same fully downloaded blog in another folder in the mode sorting files by last modified date, it turns out that some files were not downloaded, some series of posts are skipped. If set the page size to 1 and downloads pages to 1-1000 and compare again to another folder, it turns out that this mode provides the most complete downloading of recent posts. This can be seen, for example, on this blog http://yeskaipo.tumblr.com.

Thanks again for developing the program!
