### ISSUE TITLE
Few quotations 

### ISSUE THREAD

**Issue by almozayaf** [johanneszab/TumblThree#58]
1. What you mean by "Images Meta and Video Meta" in the options?

2. In the options  "Image Size (px)" , Is that for that smallest image that can be downloaded or what?

thanks.

I love you app, It so helpful

**Comment by johanneszab** [comment]
1. It creates a text file (e.g. images.txt) in the Blog folder containing possible tags, date, postid and other stuff for each photo.
2. It's the maximum size. If the size does not exist, the next lower one is downloaded.

**Comment by almozayaf** [comment]
> It's the maximum size. If the size does not exist, the next lower one is downloaded.

So for the bigger image size i need to put the biggest 1280, I was thinking it the minimum .
