### ISSUE TITLE
Universal Links Downloader

### ISSUE THREAD

**Issue by kingbode** [johanneszab/TumblThree#60]
is there any opportunity to import list of links and save them under blog or so name to be downloaded directly without scan, as they are direct links for downloads, just to be sent to download engine.

some websites in this case may require login to make you able download files from the server, may be future recover to this point.

**Comment by johanneszab** [comment]
Sure, possible is everything.

I'm not promising anything related to new features anymore since issues are already piling up here and I've to set some priorities somewhere ..
