### ISSUE TITLE
Error when loading library: Invalid JSON primitive

### ISSUE THREAD

**Issue by lionbaiter** [johanneszab/TumblThree#61]
Just downloaded the latest release, when I open it I get a 

Error 1:Could not load file in library: 
Internal error description:

Invalid JSON primitive

**Comment by johanneszab** [comment]
Download the 1.0.4.31 release, run it once to convert your database files. After that you can use the latest release. Make a backup of the _\Index\_ folder (contains the _.tumblr_ databases) before running the 1.0.4.31 release.
