### ISSUE TITLE
release 1.0.4.31 not compatible with 1.0.4.41

### ISSUE THREAD

**Issue by tringate** [johanneszab/TumblThree#64]
I used release 1.0.4.31 to convert to the two files for each blog in the index folder however that release converts the .tumblr file into an encoded file and not a human readable file like 1.0.4.32 does.  Your instructions say to convert using release .31 however those files do not work with release .41.

I am going to try to convert them a second time with release .32 after the first conversion with release .31 to see if release .41 will then be able to use the files.

**Comment by johanneszab** [comment]
Try it again.
Download the .31 release, start it once and let it load all your blogs. It immediately converts your old databases into the new ones and saves them. Close the application, then use the .41+ release as normal. That should work.

I've just re-uploaded the .31 release since there was a path inconsistency which let the .41+ release to create a new _files_files.tumblr file instead of using the converted one. I've just tested it and it works.

Do NOT use the .32 release since the same bug thing will happen there, that's why I've removed that release now.

**Comment by tringate** [comment]
Ok, I had already tried doing the .32 update and it did not work either so because this was a small subset of my total blog I simply deleted the index folder moved all the photos and deleted the individual blog photo folders then installed .41 and did a fresh update downloading the 13 blogs that made up this group.  I am making individual instances of tumblrthree for the different blog groups I have and running them one at a time as I do not really want to do a full download of every blog ever time I update.  Trying to figure out which blogs are in what group is a nightmare with everything in one massive blog so this appears to be the best way to put some sanity to it all for me.

That worked just fine but I see there is release .42 now so I will download .31 as you recommend, make my next group of blogs in this new instance, install it first as .31. convert the index files, then install .42 and give it a run for it's money.


My primary massive blog is still at version .31 and even these 13 blogs are still in that one instance.  I have no idea how many blogs are in it as it goes on for several pages.  I will update that to the new .31 and let it do whatever it does.  I hope you do not have to actually put all the blogs into the queue to have it convert the files.  It looked like just starting the program had it convert them before.

**Comment by tringate** [comment]
I just tried with a instance that runs 69 blogs, it was at the previous version .31 so I deleted the software programs and replace them with the new release .31 launched it and all the blogs appeared in the list.  I then deleted that version of software in that instance and replaced it with release .42.  I launched it and the blog list is totally empty, nothing appears.  I deleted the release .42 software and put back the updated .31 software launched the instance and all 69 blogs appeared in the blog list.

I do have another question and that is I have a new blog instance running .32, it actually was made from scratch using release .32 so everything has always been loaded in it using that release only.  Can that release instance be updated to .42, or does it need to be deleted and start over from scratch again using release .42?
It should be noted I never run two instances of tumblrthree at the same time like I was able to with tumbletwo.  Ruining them individually appears to be ok as I have not noticed any strange behavior.

I did observe that settings is the same for all instances if you use any instance to change it it changes for all of them.  For me that is fine and saves me time going around and changing each instance since I want them all the same anyway.

**Comment by johanneszab** [comment]
> I did observe that settings is the same for all instances if you use any instance to change it it changes for all of them. For me that is fine and saves me time going around and changing each instance since I want them all the same anyway.

Someone suggested we could store them within the Index folder location. And also separate the Index folder location from the download location. Basically make a _portable_ version.

It's not much code to do that, someone just has to write it.
