### ISSUE TITLE
Crawling

### ISSUE THREAD

**Issue by sup3ruser** [johanneszab/TumblThree#70]
Crawling is skipping all sorts of posts.  Appears to be posts that bloggers did not post their self, but media that the bloggers reblogged from another blogger.

2nd thing that I noticed is that, when there are multiple items in que to be crawled, the crawler doesn't automatically crawl the next blog, which forces me to have to constantly shut down app, and restart it.

What I found to work much better, is just manually adding blogs to que 1 by 1, then after that single blog is finished, just add the next blog manually.  I've even set parallel crawls/downloads to "1".  

While this does work for the time being, its extremely tedious & time consuming, and almost is taking the whole automation out of the equation, except downloading.  However, Im very aware that you've created one of the best scrapers around, and very appreciative of that, and you have my support...Im just getting a little anxious cause Im trying to update almost 1000 blogs from 1 year ago, and Im worrying that I may have to do this whole process all over again once the bugs/kinks get worked out.

Jerome

**Comment by johanneszab** [comment]
> 2nd thing that I noticed is that, when there are multiple items in que to be crawled, the crawler doesn't automatically crawl the next blog, which forces me to have to constantly shut down app, and restart it.

Again, works for me. Could you please test all this with a new settings file and new blogs? Please always do before submitting issues.

**Comment by johanneszab** [comment]
> Crawling is skipping all sorts of posts. Appears to be posts that bloggers did not post their self, but media that the bloggers reblogged from another blogger.

I also need the specific blog here where files are being skipped. I am sure it downloads reblogged post since most of the tumblr posts are simply reblogs. For example, https://wallpaperfx.tumblr.com/ is a quite small blog, only reblogs, posts get downloaded.
