### ISSUE TITLE
New Version 1.0.4.42 problem with MP4 and GIF files

### ISSUE THREAD

**Issue by tringate** [johanneszab/TumblThree#72]
I downloaded the latest veersion .42, and updated the original version .42 with this present release.  I have made a special; test instance to test the new releases as they come out to see how stable they are since some of the bugs would require a rescan of all the blogs and then I would have to go in and delete all the duplicates which are reposts of the same photo as if it was a different photo.  There are 10 of thousands of those with many showing up in the very same blog.

This latest release was tested on an existing copy of a 10 blog instance where only 7 of the blogs are actually online.

The previous .42 release appeared to work without incident, but the new release ran and while the activity for new photos was low, all of the MP4 and GIF files failed to download.  The GIF files had a size of zero bytes, and the MP4 were very strange files which windows 10 said "not available offline" when trying to display them.

No PNG files were downloaded but that is not unusual since they are not very common.  The JPG files downloaded and looked normal.

Keep in mind that this test is on an existing test instance which has been updated now a few times from previous releases.  It started life at release .31

Most of the 7 active blogs it is downloading are smaller blogs and are not very active.

I may revert this instance to become purely a test instance and stop doing the post processing so I can get a true count of the photos without any moving of them to different folders or deleting duplicates.

Tat should give me a more solid test base for the new releases before updating my other instances to a new release.  I can also give more pure information as feedback since nothing will have been done to the download results by a post processing function.

I will use the current .42 release to download the 7 active blogs once again to see if a fresh instance will properly download all file types.

I will update this report with those findings.

**Comment by tringate** [comment]
I have installed a new instance of tumblrthree version .42 and ran the identical download only looking for images and nothing else.

I still got a rather significant number of MP4, GIT, and a few JPG and even fewer PNG files with a zero byte count for their size.  I have not noticed files of zero size being downloaded before.

Another thing I notice is nearly all the files are saved with the current system date rather than the date of the original post or the re-post date, 

Using the date to determine when the file was posted would say that of the 26,724 files I just downloaded they were almost all posted today.  I would say less than a 1,000 had an older date ant time.

That probably isn't a big, but it sure makes me wonder what date is actually being used when the date usually is the instant the file is received at the clients host rather than when it was posted on tumblr.

The zero byte file size could be the new policy of tumblr not allowing the posting of explicit sex movies, but that does not explain why there are zero byte files of JPG and PNG.  They also didn't indicate they were extending that policy to animated GIF files but suddenly there is a very large number of those files now with zero byte size.

I am going to try the previous version .42 to see if the same results are obtained downloading the same set of blogs.
I am going to delete everything in the blog folder and run it again using the first .42 code.

**Comment by sup3ruser** [comment]
This may sound weird, but with the older .42 version, I noticed the zero byte files too.  I even deleted them in some of my blogs.  Then I decided to let them sit (for some experiment) and then those zero byte files actually turned into files with their correct byte sizes.  So let them sit, and they will change into their regular size.

My theory is that maybe there is some bottleneck somewhere (mostly with the hdd) and when whatever issue is resolved, then the files are transferred successfully.

Jerome

**Comment by tringate** [comment]
I have run another download using the original .42 code and the results is almost identical.  Both have a bunch of zero byte files and unlike what @sup3ruser  said they are not filling them self in with good files.
The difference in the total number of files is "1" which could be a new post since these are active blogs.

I am presently doing another test using release .31 since that is the other release available online.  It looks a bit discouraging because while it has been downloading now for awhile, all the folder are totally empty.  I do remember one of the releases didn't save a single fil.  I sure hope that isn't this release .31.
I downloaded another zip file from the wen site deleted everything in the blogs folder, deleted all the program files and did a complete fresh install and it appears that release .31 is totally broken unless it waits until after a blog has downloaded it's files and then it puts them into the folder in BLOGS.  It never worked that way before to my knowledge.

I do remember reading something about one release that it would fail to work with some operating systems but I don't remember the specifics since I have been past this release now for a fair amount of time.

I do have release .35 and .40 I could tun a test with to see how it behaves if .31 fails to download anything for me.

**Comment by tringate** [comment]
I had to abandon the crawl using release .31  On my system it is completely broken.  It never finished the first 3 blogs it tried to crawl, it just hung doing nothing and no files had been downloaded even though many files had downloaded by watching the queue.

I am not sure doing a run using release .35 is going to be of any value, as it is going to need a few more hours to complete.  It has finished 4 of the blogs, and it has no zero byte files yet in any of the blogs.  But it is also finding fewer files to download, so that release was missing some files I guess.  I may have not actually used that version myself as they were coming out fairly fast right about that time and I jumped ahead and skipped some of them.

I'll let version .35 finish and will post the results tomorrow when I get up.  I hope it will have finished by then.

I do notice that release 3.5 is taking so long because it runs into MP4 files and sits with a zero byte count for a very long time then finally gets the entire file and moves on to the next file.  Maybe that is what is happening in release 4.2 but it does not wait and just gives up and moves on??
 Once it does finish, I will search to see if some of those zero byte files in version .42 download are actually there in the version .35 download.

One thing I did not try in the version .42 downloads was to do multiple crawls to see if it would find and get the missing files.

**Comment by tringate** [comment]
I have completed my testing and discovered the following:
I tested three version , .35, .42 original, and .42 current.
Each was an instance of that version crawling the same group of 10 blogs.  Three of which were offline blogs.
I did repeated crawls, one after the other to ensure they were crawling the same sized versions of the blogs.
The two .42 crawls resulted in a total of 26,707 files each with 302 zero byte files found.
the .35 version resulted in 26,364 total files with no zero byte files.
This would indicate that there were 41 new good files that the version 42 found over the 35 version.
The finding of the zero byte files brings up two questions.
- why is there a file being detected that can not be downloaded?
- Should this detection be saved in the INDEX file and/or saved as a zero byte file in the DOWNLOAD folder?

If the reason it can not be downloaded is a fault in the scraper software then it is a bug, but if the file on the server is defective or is really zero bytes, then the question is, should it be recorded at all?

I would vote that the zero byte file is NOT saved in the download folder as it is useless and only results in a display error since there is nothing to display.  I suspect this would require a delete operation be added since the file handle has already been created.

The reason we see zero byte files during the download process is a normal thing because the file handle is created before the contents of the file can be put into it.  Normally this happens in the millisecond range and is not detectable.

There does not appear to be any relationship to the file type as zero byte files are found for most types.  The only file type I did not see such a file for was the .PNG and that is most likely because there are so few of those posted compared to the other file types.

**Comment by johanneszab** [comment]
Do you have a blog for me where I can test this behavior? If possible, small? One where there are files detected but not downloaded or are zero in size?

**Comment by tringate** [comment]
I did find a blog that will consistently save 5 zero byte MP4 files whenever I crawl it.  http://enemaboy.tumblr.com/    

I have attached the blog index folder files for this blog.  I would think if you installed release 42 and put these two files into your blogs/index folder and then add the blog to it, you could see the problem without the need to download any files.  I believe it has around 4,000 photos in it but you have no need for those.  I have deleted all of the files myself and have a empty blog folder to test it.

I hope this can help.

**Comment by johanneszab** [comment]
There are some 403 -- Forbidden replies. Here is one of the grabbed urls:
https://enemaboy.tumblr.com/video_file/t:qvRZNcgU1nTpm8gYNHEElA/147439678160/tumblr_o1x9l6pcuO1um5zcp.mp4

and this is the corresponding post:

https://enemaboy.tumblr.com/post/147439678160/neverbeensucked-captain-hardon

I cannot even see the video here in my browser, just the loading screen if I press play.

**Comment by tringate** [comment]
I click on the link and see the same thing.  Just a black window where the video should be.

Is there a way to register that the post was processed and since the size is zero not try to save it?

The reason I ask is because it tries to process these same items over and over on every crawl.  Each time leaving a zero byte file in the folder.

My usual post processing is to first use another program to remove all duplicate posts from all blogs. (many photos are duplicated between posts some are reposts, and others are the same photos posted again as new photos.  Then I look at those photos that are left and delete all those that are of no interest which in many cases is nearly all of them.
Each blog is further sorted to place all of the same file types into a sub folder of that type, so all JPG files are in a sub folder called JPG, same for PNG and so on.

The root blog folder always has only the new photos that have been downloaded since my last post processing of the photos.

Since these are useless files which result from a photo that for some reason can not be downloaded, can zero byte files not be saved, but still listed as downloaded?
