### ISSUE TITLE
[Enhancement] Ignore Reblogs Option

### ISSUE THREAD

**Issue by Gabriel11999** [johanneszab/TumblThree#8]
Giving the ability to download original content from the blog, it's just a suggestion I thought would be useful I read the wiki and looked at the documentation for something like this. The closest thing I could find was the tag system.

This website shows the desired result.
http://www.studiomoh.com/fun/tumblr_originals/

**Comment by johanneszab** [comment]
I see what you mean. All these things should be easy to implement with the current code base. I'll probably add it this week.

Thanks for the suggestion! I'll add it to the "feature requests"-page in the wiki.

**Comment by Gabriel11999** [comment]
THANK YOU SO MUCH!
