### ISSUE TITLE
Download URL list settings  

### ISSUE THREAD

**Issue by googlysmooth** [johanneszab/TumblThree#84]
When you switch on Download URL List, no media files are downloaded for that blog. 
if you subsequently uncheck it later, 
Rescan does no longer pick up download images. 
even when check for files on disk 
The counter works, but no media files are created. 
If you did not initially set it, and images were saved before, they do no longer , even if you flip the Download url list...

**Comment by johanneszab** [comment]
Works for me again here.

You do not mean the same file twice, right? Either it's downloaded in the url list, or as file, but obviously not both. I've just tested a large blog here, downloaded 50 pictures as binary file, then 500 picture urls in the list, then 50 pictures again as file. No problem what so ever.

**Comment by johanneszab** [comment]
Can someone else verify this?

**Comment by googlysmooth** [comment]
So what does the rescan and check file on disk mean then ? 
Not sure I get the concept... If I wanted to re-download, what settings can I use ?
