### ISSUE TITLE
[Feature Request] File Rename/Numbering Option

### ISSUE THREAD

**Issue by JAK0723** [johanneszab/TumblThree#85]
Would it be possible to add an option to number the files? I like to ensure that the files are ordered correctly. 
The only way I am able to do this now is to set the number of connections to 1, so that each file is downloaded individually, in order. I can then sort by date modified to view the correct order, though this isn't a perfect solution. An option that would add a number to the file names that shows their original order would be very helpful.

**Comment by JAK0723** [comment]
The update seems to be working very well, with the original 'date modified' allowing me to sort posts properly. The only problem I have noticed is the ordering of files within posts. For example, the downloaded files for one post are ordered (descending date modified) as:
"tumblr_oqmw7qTxBa1sgzgnoo1_1280.jpg", "tumblr_oqmw7qTxBa1sgzgnoo2_1280.jpg", "tumblr_oqmw7qTxBa1sgzgnoo3_1280.jpg", "tumblr_oqmw7qTxBa1sgzgnoo4_1280.jpg"

It is clear that the pattern for setting the 'modified date' is the file number in numerical order. By 'file number' I mean the number just before the resolution ("tumblr_oqmw7qTxBa1sgzgnoo2_1280.jpg" -> file number is '2'). I am not certain how tumblr goes about numbering their files, they are probably numbered in the order the files are uploaded. However, this order is not how the images are numbered in the posts themselves, as the artist arranged them. For the above example, instead of going in numerical order "1, 2, 3, 4" the post is instead arranged as "3, 2, 4, 1".

This wouldn't be a problem for blogs where every post only contains a single image. However, for blogs that post several images per post which are supposed to be viewed in a specific order, this can be a substantial problem. To correct this, the order in which the files are downloaded (or how they are set to be ordered) should reflect how the images are arranged, not how the files are numbered.

**Comment by johanneszab** [comment]
I see. It's possible to get the sequence of the photosets, I'm just not sure right now how one would properly implement this.
