### ISSUE TITLE
Difficulties with downloading the image metadata in the latest versions

### ISSUE THREAD

**Issue by Taranchuk** [johanneszab/TumblThree#87]
When I today on the latest version of the program (1.0.4.53) uploaded a dozens of blogs to the queue and set the download mode for only image metadata, it turned out that on some blogs only a part of the metadata is downloaded, the rest are skipped, and on some blogs the download stops at all. And constantly flashed error Limit Exceeded, although in the settings I changed the values to low connections but it did not help. When I tried to download the image metadata in the version 1.0.4.24, which has remained on my computer from early releases, all the downloads went without problems and completely ended although all the connection values ​were standard and the error of the Limit Exceeded did not appear at all. Also tested the version v1.0.4.47 and v1.0.4.48, there also appeared difficulties with downloading metadata images. And I also compared files from different version and it turned out that the downloaded metadata files from the version 1.0.4.24 have a larger size than the same files from the latest versions. Perhaps something is wrong with the code of latest versions. Could you check this?
P.S. If you need blogs for testing, I attached the list of blogs in case if you need to. These are the same blogs with which I have difficulties with downloading their image metadata on new versions of the program.
[tumblr25.txt](https://github.com/johanneszab/TumblThree/files/1058300/tumblr25.txt)

**Comment by johanneszab** [comment]
Works fine for me. I've just downloaded 20.000 image metadata, there was no error in visual studio.

Do you use the Russian localization? Can you set the _posts per page_ to 50 and redo your tests?

I've actually added some more metadata, the original _reblog url_ and original _reblog username_. So the file size should actually increase. But if there are any weird characters in those strings, the localization parsing might fail and skip the whole meta data. But it seems to work here.

So I'm personally guessing it's something with your settings. Set the _posts per page_ to 50 and leave it there. The scanning is done via the tumblr api and access to it is rate limited. So lowering the posts per page value might decrease the performance in general.

**Comment by Taranchuk** [comment]
No, I do not use the Russian localization. I set the posts per page to 50 and still metadata is only partially downloaded. Previously I in the details view of the blogs set the posts per page to 1 because in this mode the program downloaded completely all the specific posts, in the mode of downloading the posts per page to 50 the program does no do this completely. I tried to delete the setting files and restart the program, it did not help, also tried to activate the portable mode, this also did not help. What else to do, I do not know. It remains only to continue to use the old version to download completely the image metadata. Other functions such as downloading blogs completely and downloading specific posts work fine in the new version without error limit exceeded. Also I found that if simultaneously download images and image metadata, then such an error does not arise and everything downloads normally. But when I download only image metadata without downloading images, then problems begin to appear.
P.S. If there are errors in the text, sorry, I'm not native English.

**Comment by johanneszab** [comment]
Can you send me/upload one incomplete and one complete meta data file, so two files, of one blog? And the url of that blog?

Then I can compare them and see exactly what's going on without trying around myself.

Thanks!

**Comment by Taranchuk** [comment]
OK. Send you two metadata files- one completed from the old version of the program, the second unfinished from the new version? Or two metadata from the new version? If you need both downloaded from the new version, then you need to wait a bit, for this I have to download the entire blog with images and metadata, and then delete this blog and add again this blog to download separately only the metadata.

**Comment by johanneszab** [comment]
No, send me the complete meta data from the old version, and the incomplete from the new one. That's perfect.

Thanks! I'll take a look into them later this day.

**Comment by Taranchuk** [comment]
OK. But I just finished downloading the blog with images and the image metadata file, therefore, I now have three metadata files from the same blog. Just in case, attached them all, if you only need a complete metadata file from the old version and incomplete from the new one, do not download the third file.
The first (images - complete from 1.0.4.24 version.txt) is the complete file from the old version.
The second one (images - incomplete from 1.0.4.53 version.txt) is incomplete from the new version, which was downloaded in the mode downloading only image metadata.
The third one (images - complete from 1.0.4.53 version.txt) is the complete file from the new version, obtained by downloading the entire blog with images and image metadata.
Url of this blog: http://sintillator.tumblr.com
But to be honest, I do not really understand how comparing metadata will help clarify the situation. After all, this error appears at different times, not in the same place at specific post, say, if this blog has 11 thousand posts, then up to 7 thousand posts downloading the metadata can go quietly, and then this error of limit exceeded appears and download stops while the scanning goes on, then after some time downloading continues but not at the place where it was interrupted, but at the place where the scan is going currently. And if delete the blog and the metadata file and add this blog to the program a second time, then downloading can go up to 5 thousand or up to 9 thousand blogs, and then this error appears and the download stops while scanning goes on, then download are resume after some time, but in the time interval download stops and thus obtained partially downloaded metadata. If there are errors in the English text, sorry, I hope I clearly described the crux of the problem.
[images - complete from 1.0.4.24 version.txt](https://github.com/johanneszab/TumblThree/files/1066448/images.-.complete.from.1.0.4.24.version.txt)
[images - incomplete from 1.0.4.53 version.txt](https://github.com/johanneszab/TumblThree/files/1066450/images.-.incomplete.from.1.0.4.53.version.txt)
[images - complete from 1.0.4.53 version.txt](https://github.com/johanneszab/TumblThree/files/1066449/images.-.complete.from.1.0.4.53.version.txt)

**Comment by johanneszab** [comment]
Ah, okay. Now I understood it.

There is nothing I can do then I guess. Try to lower the connections to the api. What are your current values? 95 connections per 60 seconds? For my connection here it works without triggering the limit, but maybe you have to lower it a bit, like 90 per 60 seconds and try if that works. Maybe for some people there is no limit at all. At my work with a static IP and public hostname there seems to be be no issues at all and you can completely disable the api limiter.

It was probably luck that you didn't trigger the api limit with the 1.0.4.24 version. It has no detection built-in and just continues normally without saying anything. It should download less posts as it just hits the limits and discards the invalid information. But it depends of course on several factors. Maybe you did load only one blog per time with the 1.0.4.24 version, but multiple with the current version and for me the rate limit appears at its earliest at around 250 connections made, regardless of the timeframe. So I can completely scan a blog with 10000 posts in 5 seconds, or 20 seconds. There seems to be no difference at all if the number of posts is rather small. But both settings will hit the limit if it contains more than 10.000 posts.

I haven't found anything in the official tumblr documentation about the rate limit of the tumblr api v1. And the default values (95 connections per 60 seconds) are just a guess and _seem_ to work _here_.

PS: When I download here a blog with the v1.0.4.18, the amount of downloaded posts/meta data varies as hits the limits and is around 1x.xxx.

**Comment by Taranchuk** [comment]
I doubt that it was just luck, that it didn't trigger the api limit. Because I once again uploaded hundreds of blogs to the queue in this old version and set mode of downloading image metadata and there was not a single error. In addition, I used to use this version a lot before, and did not see any errors in downloading metadata. This version is reliable for me in terms of downloading metadata, there have been downloaded for all time somewhere several thousand metadata files. And there is a limit checker here, I see a file Rate Limiter among the files of the version 1.0.4.24 and there is a limit tumblr api connections item in the settings. I've just looked at the values of the connections in the old version, it turns out there was even more vaules of connections than in the new version. 120 connections per 60 seconds. And the value of parallel blogs and parallel connections is on 2 blogs and 25 connections. And there is no problem with downloading metadata. I have now compared the numbers of found lines "Post ID: " in the metadata files with the numbers of posts shown in details view of the blogs in the program and I did not find a single discrepancy, it seems that all the metadata downloaded normally and the progress bar in the program shows full load, whereas in the new version the numbers of found lines "Post ID: " did not coincide with the actual number of posts of the blogs and the progress bars were not completely filled and constantly flashed error Limit Exceeded. I tried lowering the connections to 40 per 60 seconds in the new version and this error continues to appear and I gave up the attempt after seeing how this has a negative impact on the download speed. So I will alternate both versions (the new for downloading images and old for downloading metadata).

**Comment by johanneszab** [comment]
I don't know.

Sounds like something I cannot fix since it depends on the response of the tumblr servers. I've just tested grabbing 31000 image meta data right now with the 1.0.4.31 and 1.0.4.55 release with 120 connections per 60 seconds, both didn't hit the limit and worked fine. 
Whereas I'm sure that I've hit multiple times the limit with 100 connections per 60 seconds at around 13000 posts.
So maybe It even depends on the workout of the servers or the time. 

I've written above that I couldn't figure out exact values and there is no official documentation about it.

I can reopen this if it makes you somehow happy. Maybe there is someone who is willing in digging around this and figure this out. It surely sounds like more time consuming, and thats something I don't have right now.

**Comment by Taranchuk** [comment]
I'm not a programmer, but it seems to me that there may be something wrong with the code of the program, at least in terms of downloading the metadata. It's just strange for me, if the reason is in inaccessible tumblr servers, then why does the version v1.0.4.24 always download the metadata completely without any problems, and the 1.0.4.54 version does not download them completely? Also I searched at the computer for archives of earlier versions of the program and found one more 1.0.4.29 version. I unzipped this, launched the program, set the mode of download the metadata, clicked the download button and it passed without any problems, the files were downloaded completely. I decided to download the version 1.0.4.31 for testing, and this version already has the same difficulties with downloading metadata like in the new versions. And I noticed something in common with versions v1.0.4.24 and 1.0.4.29 and than versions 1.0.4.31 and newer are different from them. This is file RateLimiter.dll, which lies in v1.0.4.24 and v1.0.4.29 folders and which is not in version 1.0.4.31 and later versions, but instead it there lies Guava.RateLimiter.dll file in their folders. Maybe something is wrong with this file so there are difficulties with metadata downloading? It seems more likely to me, as on 1.0.4.31 versions and newer difficulties were noticed almost immediately, but on 1.0.4.24 and 1.0.4.29 they were not noticed at all, everything went smoothly. And the values of the connections in the settings in version 1.0.4.31 are absolutely the same as in versions 1.0.4.24 and 1.0.4.29. If necessary, I can upload the archives of these versions for comparison.

**Comment by johanneszab** [comment]
![55_complete_12060](https://user-images.githubusercontent.com/1684561/27020463-e9f35df0-4f41-11e7-8dd7-ccd1c5aa2de2.png)

I've just downloaded multiple times your blog with the .55 release, only the image data, with 120 connections per 60 seconds. No problems whatsoever.

I don't say I don't believe you. You probably use TumblThree more than me, but I'm probably not doing anything here right now with my time available.

**Comment by Taranchuk** [comment]
Ok, it's okay then. Then I'll just use the old version if I need to separately download image metadata. This is not a problem for me. I will alternate the old and new versions of the program. Thank you for developing the program!
