### ISSUE TITLE
creates files_files 

### ISSUE THREAD

**Issue by johnflint1985** [johanneszab/TumblThree#89]
Once I add new blogs it creates a file which  for example reads:  nonsense_files_files.tumblr so if you want anything to be downloaded you need to change the name of the file to nonsense_files.tumblr.

why does it do that? Is there any reset that I can go to the original way it was adding new blogs?

**Comment by johanneszab** [comment]
Version of TumblThree? That happens to __newly__ added blogs? Otherwise see [my answer in this issue](https://github.com/johanneszab/TumblThree/issues/64#issuecomment-294370372).

**Comment by johanneszab** [comment]
Possible duplicate of #64.
