### ISSUE TITLE
[Minor Bug] Duplicate Entries from "Check Clipboard"

### ISSUE THREAD

**Issue by Gabriel11999** [johanneszab/TumblThree#9]
When copying a URL from my web browser it creates a duplicate entry. It's not that big of a deal just mostly an annoyance. I have tested this in Chrome and Edge, but does not appear to do it in Notepad. Closing TumblThree and opening it again seems to delete the extra entries.

Using Windows 10 Anniversary with Google Chrome

Steps to Reproduce:
1. Open TumblThree
2. Open web browser (Google Chrome/Edge)
3. Copy URL from address bar in browser with Crtl + C

Result:
http://i.serealia.ca/2016/10/TumblThree_aTYlu2g_2016-10-31_15-00-20.png

If Crtl + C is spammed it produces multiple entries:
http://i.serealia.ca/2016/10/TumblThree_34YEdf1_2016-10-31_14-55-11.png

**Comment by Gabriel11999** [comment]
I also found a number of other bugs if you'd like me to post them. Im not sure if you're really interested x3
Oh, and do you take donations?

**Comment by johanneszab** [comment]
Just post them here or create a new entry for each bug is probably even better. I currently don't use the crawler for myself at all so I will miss many bugs in my short test runs during development.

If you want, you can donate via [my website](https://www.jzab.de/). There is a paypal and flattr box on the right side.

**Comment by johanneszab** [comment]
It somehow doesn't happen for me but I see that it is possible. Also someone else on my webpage suggested the same. Maybe it's OS dependent..

I'll fix it over the next days and you'll have to tell me if the issues still persists afterwards for you.
