### ISSUE TITLE
Download "_raw" instead of "_1280"

### ISSUE THREAD

**Issue by JAK0723** [johanneszab/TumblThree#92]
I have recently discovered that it is possible to access the original unrestricted image file by replacing the resolution specification with "_raw". While "_1280" files were thought to be the largest accessible size, it turns out that "_raw" files can be larger if the original file uploaded had a higher resolution than 1280 x 1920.

**Comment by johanneszab** [comment]
Thanks for the info! I've just checked it and it seems to the case.

I'll add it within the next days.

**Comment by johanneszab** [comment]
Thanks again.
