### ISSUE TITLE
Add Support for the Raw Image Sizes?

### ISSUE THREAD

**Issue by Gho57X90** [johanneszab/TumblThree#94]
It has been going around recently that you can download bigger than the '1280' sized images by replacing the number with 'raw'. Is it possible to add support for downloading this image size?

Example:
http://68.media.tumblr.com/b7b3e9116c159995835d2082853f72a7/tumblr_noj18q9xxG1ro9jlvo1_1280.jpg
http://68.media.tumblr.com/b7b3e9116c159995835d2082853f72a7/tumblr_noj18q9xxG1ro9jlvo1_raw.jpg

**Comment by johanneszab** [comment]
Duplicate of #92 #93.

**Comment by Gho57X90** [comment]
Ah, my apologies.
