### ISSUE TITLE
Is it possible to add reblog tags and caption to metadata?

### ISSUE THREAD

**Issue by Taranchuk** [johanneszab/TumblThree#95]
In the metadata, there are new entries such as Reblog Url and Reblog Name. For me, this is a very good addition to metadata, it's useful to know the new blogs. There is a question, is it possible to add also Reblog Photo Caption and Reblog Tags (means the original tags and the caption from the blog where the reblog was made), if it is possible to get from tumblr api? Thanks!

**Comment by johanneszab** [comment]
Nothing in the api about this.

It's certainly possible to grab the referenced reblog url page and check for tags on this page. That however requires some more work to properly implement and downloading plenty of referenced web pages just for tags.

I'll probably don't do this myself as I don't know if that's a good addition honestly. But if someones cares to implement this, I'm open to any code.

**Comment by Taranchuk** [comment]
Well, I agree, for others it will not be a good addition, it seems this is just for me it will be. Thanks for the answer. I probably better close this topic, because I do not think that someone else will implement it. Thanks again!
