### ISSUE TITLE
Ability to download search url

### ISSUE THREAD

**Issue by boredsilly** [johanneszab/TumblThree#97]
Say I do a search on the front page for an artist (e.g Peter Elson) I get the following url:
https://www.tumblr.com/search/Peter+Elson

This contains a selection of his images

Would it be possible to add this search result as a download option somehow?

**Comment by Taranchuk** [comment]
I previously somehow requested a similar function, namely function download throughout the Tumblr by some keywords. So for example, download all images by keywords Star Wars or something like that. I would really like this opportunity, for some people this function would be better even than the function of downloading blogs.

**Comment by johanneszab** [comment]
It's probably already mostly implemented in [the TumblrLikeByDownloader class](https://github.com/johanneszab/TumblThree/blob/master/src/TumblThree/TumblThree.Applications/Downloader/TumblrLikedByDownloader.cs). Someone just has to figure out how the pagination works (i.e. getting the second page of the search). It's sadly different everywhere at tumblr. The archive works with _?before_time=1469632202_, the blogs with _/page/_ the api yet again differently.

**Comment by boredsilly** [comment]
According to httpfox it seems to be issuing:

https://www.tumblr.com/search/peter+elson/post_page/2

I'm not a csharp coder though so cannot really do it myself.

**Comment by johanneszab** [comment]
If someone wants to implement this, this might be helpful. Here is how I've setup the HttpWebRequest for the various different GET requests in the different TumblrDownloader:
https://github.com/johanneszab/TumblThree/blob/svc/src/TumblThree/TumblThree.Applications/Downloader/TumblrDownloader.cs#L213

https://github.com/johanneszab/TumblThree/blob/svc/src/TumblThree/TumblThree.Applications/Downloader/TumblrLikedByDownloader.cs#L116

**Comment by johanneszab** [comment]
I've added support for downloading files from the search [in this branch](https://github.com/johanneszab/TumblThree/tree/svc). The requests however are not working and are returned with a 403 error (permission denied).

I've tried to implement it with the help of the Chrome Developer Tools, but the POST requests probably need some more fine tuning in the body since they contain a whole lot of stuff I've not figured out yet. If someone feels like poking around, the boilerplate code is already done.

**Comment by Taranchuk** [comment]
> but the POST requests probably need some more fine tuning in the body since they contain a whole lot of stuff I've not figured out yet. If someone feels like poking around, the boilerplate code is already done.

I'm not a programmer at all, only an ordinary user, but I would like to help somehow if it is possible by my own efforts. Whether it is necessary to pick up the correct URL address to tumblr search page or something in this sort? Or if not, then сould you explain what is the problem and what needs to be done to solve this problem?

**Comment by Taranchuk** [comment]
Sorry that again I'm disturbing you about this issue, but just 7 days have passed from my question and since then there has been no answer. For me, the function of downloading images from the search page on the Tumblr is very important, so I would like to help somehow if this is possible by my capabilities.

**Comment by johanneszab** [comment]
The first page can be downloaded using a GET request without any authentication. Thus, downloading the first page works without any problems.

For further browsing using the the https://www.tumblr.com/search/searchterm/post_page/sitenumber POST you need a Header called _X-tumblr-form-key_ which seems to be some kind of nonce similar as in OAuth.

When I leave my browser open for a while the same requests that previously worked without any problems are denied with a 403 error. Thus, the _X-tumblr-form-key_ has a lifetime and needs to be newly generated for each search, probably by using some kind of javascript and maybe even depends on a user cookie. 

![tumblrsearch_post_request](https://user-images.githubusercontent.com/1684561/29554228-a1a52b40-871e-11e7-8140-de93270f718e.png)

**Comment by johanneszab** [comment]
I've seen that there is also a way to search using tags? It it similar or completely different?

It uses GET requests and is easy to implement. E.g, for "searching for cars":
https://www.tumblr.com/tagged/car?before=2000

**Comment by johanneszab** [comment]
hmm .. I've found the key from the search, but the one in the browser seems to be hashed in some way. It always starts with _![some digits]|_ whereas the one returned from the WebRequest does not.

The POST responses indicate now a successful request (200), but the html element is always empty.

**Comment by johanneszab** [comment]
Okay, you might give it a try. I don't know if it ever stops, probably not. Maybe we have to compare all the returned images and see if they stay the same for a new search with an increased pagination.

There are also a lot of parameters someone has to figure out. In the screenshot, you can see blogs_before, num_of_blogs_shown, before, blog_page. num_of_posts_shown and post_page is probably the number of returned posts and the page from the pagination. I've tried only changing them, but after around ~80 posts, the returned posts don't change anymore and one basically crawls the same page over and over again.

![tumblrsearch_post_request_parameter](https://user-images.githubusercontent.com/1684561/29566615-acc845f8-874a-11e7-93a7-5febfd9db049.png)

**Comment by johanneszab** [comment]
Okay, I've also implemented a downloader for the https://www.tumblr.com/tagged/keyword search as it seems to return more than just 50-150 posts.

I've figured out that my search implementation wasn't faulty at all as I understand it now. You can see it for yourself if you open the browser and scroll down for about 20 secs in the search, you'll reach an end. Thus, imho it's quite useless was quite a waste of time :/

![tumblr_search_limit](https://user-images.githubusercontent.com/1684561/29583962-82bbe0b6-8782-11e7-96f4-29f228ee998b.png)

**Comment by tumblthreefan** [comment]
Would it be possible to implement this at the blog level? For example, only download posts/images/videos/etc. from [this blog](https://staff.tumblr.com/tagged/features) with the tag #features.

**Comment by johanneszab** [comment]
You can already, can't you?

Just put "features" in the tag column. It's even written [on the main page](https://github.com/johanneszab/TumblThree).
