### ISSUE TITLE
'Remove Blog' Confirmation

### ISSUE THREAD

**Issue by A-Cat-Named-Tiger** [johanneszab/TumblThree#98]
Since I clicked 'Remove Blog' instead of 'Remove from Queue' for all blogs, I write this.

Wouldn't it be better if there was a confirmation before deleting blog index? Or just moving files into recycle bin would be fine, too. 

Thanks for your hard work.

**Comment by johanneszab** [comment]
I won't add this since I hate those dialogs. Either you want to delete, or not. Then simply don't press the button ;)

If anyone adds this as an option, okay. But personally, I won't waste my time on this..
